Repository redis/redis, pull requests merged in 2019-12, with the labels that each got.

#6384 Getting region date per process in Darwin
  src/zmalloc.c
  src/zmalloc.h
Labels: portability

#6257 Modules must have execute permissions to load
  src/module.c
Labels: security

#5916 Add module APIs for custom authentication
  runtest-moduleapi
  src/acl.c
  src/module.c
  src/modules/Makefile
  src/modules/helloacl.c
  src/networking.c
  src/redismodule.h
  src/sentinel.c
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/auth.c
  tests/unit/moduleapi/auth.tcl
Labels: REVIEW-AND-MERGE

#6615 Wrap also propagate as multi
  src/module.c
  src/multi.c
  src/scripting.c
  src/server.c
  src/server.h
  src/t_list.c
Labels: critical bug, replication
