Repository redis/redis, pull requests merged in 2020-12, with the labels that each got.

#7993 Adds pub/sub channel patterns to ACL
  redis.conf
  src/acl.c
  src/config.c
  src/multi.c
  src/pubsub.c
  src/redis-cli.c
  src/scripting.c
  src/server.c
  src/server.h
  tests/unit/acl.tcl
  tests/unit/moduleapi/blockedclient.tcl
Labels: state:major-decision, state:needs-doc-pr

#8085 Improve dbid range check for SELECT, MOVE, COPY
  src/db.c
  src/object.c
  src/server.h
  tests/unit/keyspace.tcl
Labels: state:to-be-merged

#8118 Getset fix
  src/t_string.c
  tests/unit/type/string.tcl
Labels: state:to-be-merged

#8108 Backup keys to slots map and restore when fail to sync if diskless-load type is swapdb in cluster mode
  src/bio.c
  src/db.c
  src/lazyfree.c
  src/replication.c
  src/server.h
  tests/cluster/tests/17-diskless-load-swapdb.tcl
Labels: release-notes

#8072 Adds exclusive ranges to X[REV]RANGE
  src/stream.h
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7954 Limit the main db and expires dictionaries to expand
  src/config.c
  src/db.c
  src/dict.c
  src/dict.h
  src/evict.c
  src/expire.c
  src/latency.c
  src/lazyfree.c
  src/module.c
  src/redis-benchmark.c
  src/redis-cli.c
  src/sentinel.c
  src/server.c
  src/server.h
  src/t_zset.c
  tests/unit/maxmemory.tcl
  tests/unit/other.tcl
  utils/hashtable/rehashing.c
Labels: release-notes, state:to-be-merged

#8097 Make sure we do not propagate nested MULTI/EXEC
  src/module.c
  src/multi.c
  src/scripting.c
  src/server.c
  src/server.h
  tests/modules/keyspace_events.c
  tests/unit/moduleapi/keyspace_events.tcl
Labels: state:to-be-merged

#8100 prevent client tracking from causing feedback loop in performEvictions
  src/evict.c
  tests/unit/maxmemory.tcl
Labels: state:to-be-merged

#8113 Add CLIENT INFO subcommand.
  src/networking.c
  src/redis-cli.c
  tests/unit/introspection.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr

#8150 Fix setproctitle related crashes.
  src/setproctitle.c
Labels: release-notes

#8130 Adds exclusive range query interval to XPENDING
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: state:major-decision, state:needs-doc-pr

#8141 Handle output buffer limits for Module blocked clients
  src/networking.c
  tests/modules/blockedclient.c
  tests/unit/moduleapi/blockedclient.tcl
Labels: release-notes, state:to-be-merged

#8112 Add module data-type support for COPY.
  src/db.c
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/datatype.c
  tests/unit/moduleapi/datatype.tcl
Labels: state:major-decision

#8076 TLS: Add different client cert support.
  redis.conf
  src/config.c
  src/sentinel.c
  src/server.h
  src/tls.c
  tests/instances.tcl
  tests/support/benchmark.tcl
  tests/support/cli.tcl
  tests/support/redis.tcl
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/introspection.tcl
  tests/unit/tls.tcl
  utils/gen-test-certs.sh
Labels: approval-needed, release-notes, state:major-decision

#8094 Add GEOSEARCH/GEOSEARCHSTORE command
  src/geo.c
  src/geohash.h
  src/geohash_helper.c
  src/geohash_helper.h
  src/server.c
  src/server.h
  tests/unit/geo.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr

#8149 Modules: add defrag API support.
  runtest-moduleapi
  src/defrag.c
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/Makefile
  tests/modules/defragtest.c
  tests/support/util.tcl
  tests/unit/moduleapi/defrag.tcl
Labels: approval-needed, release-notes, state:major-decision

#8155 Add total_forks to INFO STATS
  src/server.c
  src/server.h
Labels: approval-needed, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8136 redis-cli: make returning error exit code possible when command execution fails
  src/redis-cli.c
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8153 Add module event for repl-diskless-load swapdb
  src/db.c
  src/module.c
  src/redismodule.h
  tests/modules/testrdb.c
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#6728 cli fix for correct db number
  src/redis-cli.c
Labels: state:to-be-merged

#8132 Expose Redis main thread cpu time, and scrape system time via INFO command.
  src/server.c
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8187 Redis 6.2 RC1.
  00-RELEASENOTES
  src/help.h
  src/version.h
Labels: state:major-decision

#8140 Fix some wrong server.dirty increments
  src/db.c
  src/hyperloglog.c
  src/t_hash.c
  src/t_list.c
  src/t_set.c
Labels: state:to-be-merged

#8200 Handle binary safe string for REQUIREPASS and MASTERAUTH directives
  src/config.c
  src/replication.c
  src/server.h
  tests/unit/auth.tcl
Labels: state:to-be-merged

#5954 Not over-allocate client query buffer when reading large objects.
  src/networking.c
Labels: state:to-be-merged

#8222 Fix PFDEBUG commands flag
  src/server.c
Labels: release-notes

#8216 Remove read-only flag from non-keyspace cmds, MULTI propagation changes
  src/cluster.c
  src/module.c
  src/multi.c
  src/scripting.c
  src/server.c
  src/server.h
  tests/modules/propagate.c
  tests/unit/moduleapi/propagate.tcl
  tests/unit/multi.tcl
Labels: release-notes, state:to-be-merged

#8231 Fix issue where fork process deletes the parent pidfile
  src/debug.c
  src/server.c
Labels: release-notes

#8133 Fix random element selection for large hash tables.
  src/Makefile
  src/dict.c
  src/dict.h
  src/mt19937-64.c
  src/mt19937-64.h
  src/redis-benchmark.c
  src/redis-check-rdb.c
  src/redis-cli.c
  src/server.c
Labels: release-notes, state:to-be-merged

#8213 Fix the problem that Darwin memory leak detection may fail
  tests/support/server.tcl
Labels: state:to-be-merged

#8039 Cleanup key tracking documentation and table management
  redis.conf
  src/aof.c
  src/bio.c
  src/bio.h
  src/db.c
  src/lazyfree.c
  src/replication.c
  src/server.h
  src/tracking.c
Labels: approval-needed, release-notes

#8214 syncWithMaster / sendSynchronousCommand refactory, cleanup and pipelineinig
  src/replication.c
  src/server.h
Labels: release-notes, state:to-be-merged

#8179 Adds count to L/RPOP
  src/server.c
  src/server.h
  src/t_list.c
  tests/unit/type/list.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7309 Tracking: add CLIENT TRACKINGINFO subcommand
  src/networking.c
  tests/unit/tracking.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7377 Make the protocol-version argument of HELLO optional
  src/networking.c
  src/sentinel.c
  src/server.c
  tests/unit/tracking.tcl
Labels: approval-needed, release-notes, state:major-decision

#8249 Fix memory leaks in error replies due to recent change
  src/networking.c
  src/scripting.c
  src/server.c
Labels: state:to-be-merged

#8217 Added Errorstats info section to enable keeping track of the different errors that occur within Redis; Added failed_calls to commandstats
  src/config.c
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
  tests/cluster/tests/18-info.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/info.tcl
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged
