Repository redis/redis, pull requests merged in 2020-01, with the labels that each got.

#6715 Fix petential cluster link error.
  src/config.c
Labels: cluster, critical bug

#6703 Blocking XREAD[GROUP] should always reply with valid data (or timeout)
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
  tests/unit/type/stream.tcl
Labels: streams

#6114 Rename rdb when replica finish receiving rdb asynchronously
  src/replication.c
Labels: latency

#6699 Modules: Fix blocked-client-related memory leak
  src/module.c
  tests/modules/blockonkeys.c
  tests/unit/moduleapi/blockonkeys.tcl
Labels: modules system
