Repository redis/redis, pull requests merged in 2020-10, with the labels that each got.

#7858 support sentinel myid subcommand
  src/sentinel.c
Labels: class:feature, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7881 Allow blocked XREAD on a cluster replica
  src/cluster.c
  tests/cluster/tests/16-transactions-on-replica.tcl
  tests/instances.tcl
Labels: backport-candidate, release-notes

#6929 Adds new pop-push commands (LMOVE, BLMOVE)
  src/blocked.c
  src/module.c
  src/server.c
  src/server.h
  src/t_list.c
  src/t_stream.c
  src/t_zset.c
  tests/integration/replication.tcl
  tests/support/util.tcl
  tests/unit/introspection-2.tcl
  tests/unit/type/list.tcl
Labels: state:major-decision, state:to-be-merged

#7886 Modules: Add RM_GetDetachedThreadSafeContext().
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision

#7866 Module API: Add RM_GetClientCertificate().
  src/connection.h
  src/module.c
  src/redismodule.h
  src/tls.c
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision

#7865 Add Module API for version and compatibility checks
  src/module.c
  src/redismodule.h
  src/version.h
  tests/modules/blockedclient.c
  tests/modules/hooks.c
  tests/modules/keyspace_events.c
  tests/modules/misc.c
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, state:to-be-merged

#7910 support NOMKSTREAM option in xadd command
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7888 Support ACL for Sentinel Mode
  sentinel.conf
  src/acl.c
  src/sentinel.c
  src/server.c
  src/server.h
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7919 fix double fclose in aofrewrite
  src/aof.c
Labels: state:to-be-merged

#7920 WATCH no longer ignores keys which have expired for MULTI/EXEC.
  src/expire.c
  tests/unit/multi.tcl
Labels: release-notes, state:needs-code-doc, state:to-be-merged

#7942 fix invalid 'failover' identifier in cluster slave selection test
  tests/cluster/tests/05-slave-selection.tcl
Labels: state:to-be-merged

#7940 Adds command introspection to Sentinel
  src/sentinel.c
Labels: state:major-decision, state:needs-doc-pr, state:to-be-merged

#7948 Speedup cluster failover.
  src/cluster.c
  src/cluster.h
Labels: state:to-be-merged

#7381 Disable THP if enabled
  redis.conf
  src/config.c
  src/latency.c
  src/latency.h
  src/server.c
  src/server.h
Labels: release-notes, state:major-decision, state:to-be-merged

#7952 add acl related config in sentinel.conf
  sentinel.conf
Labels: state:to-be-merged

#7936 Optionally (default) fail to start if requested bind address is not available
  redis.conf
  src/anet.c
  src/server.c
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7913 Add local address to CLIENT LIST, and a CLIENT KILL filter.
  src/anet.c
  src/anet.h
  src/aof.c
  src/connection.c
  src/connection.h
  src/networking.c
  src/replication.c
  src/sentinel.c
  src/server.h
Labels: state:major-decision, state:needs-doc-pr, state:to-be-merged
