Repository redis/redis, pull requests merged in 2020-07, with the labels that each got.

#7536 This PR introduces a new loaded keyspace event
  runtest-moduleapi
  src/module.c
  src/rdb.c
  src/redismodule.h
  src/server.h
  tests/modules/Makefile
  tests/modules/keyspace_events.c
  tests/unit/moduleapi/keyspace_events.tcl
Labels: state:major-decision, state:to-be-merged

#7562 Add SignalModifiedKey hook in XGROUP CREATE with MKSTREAM option
  src/t_stream.c
Labels: state:to-be-merged

#7443 Avoid an out-of-bounds read in the redis-sentinel
  src/sentinel.c
Labels: state:to-be-merged

#7446 Show threading configuration in INFO output
  src/networking.c
  src/server.c
  src/server.h
Labels: state:to-be-merged

#7571 broadcast a PONG message when slot's migration is over, which may red…
  src/cluster.c
Labels: class:optimization
