Repository redis/redis, pull requests merged in 2020-08, with the labels that each got.

#7593 Add a ZMSCORE command returning an array of scores.
  src/server.c
  src/server.h
  src/t_zset.c
  tests/support/cluster.tcl
  tests/unit/type/zset.tcl
Labels: class:feature, release-notes, state:major-decision, state:to-be-merged

#6702 Fix tests/cluster/cluster.tcl about wrong usage of lrange.
  tests/cluster/cluster.tcl
Labels: state:to-be-merged

#7612 add force option to 'create-cluster create' script call
  utils/create-cluster/create-cluster
Labels: state:to-be-merged

#7611 reintroduce REDISCLI_CLUSTER_YES env variable in redis-cli
  src/redis-cli.c
Labels: state:needs-doc-pr, state:to-be-merged

#7092 Prevents default save configuration being reset...
  src/server.c
Labels: release-notes

#7590 fix migration's broadcast PONG message, after the slot modification
  src/cluster.c
Labels: class:optimization

#7323 Fix applying zero offset to null pointer when creating moduleFreeContextReusedClient
  src/module.c
  src/server.c
  src/server.h
Labels: state:to-be-merged

#7623 fix memory leak in ACLLoadFromFile error handling
  src/acl.c
Labels: state:to-be-merged

#7579 Add Sentinel Subcommand Help
  src/sentinel.c
Labels: state:to-be-merged

#7577 see #7544, added RedisModule_HoldString api.
  src/module.c
  src/redismodule.h
  tests/modules/keyspace_events.c
  tests/unit/moduleapi/keyspace_events.tcl
Labels: state:major-decision, state:to-be-merged

#7625 Avoid redundant calls to signalKeyAsReady
  src/blocked.c
  src/db.c
  src/module.c
  src/server.h
  src/t_stream.c
Labels: class:optimization

#7615 Implement SMISMEMBER key member [member ...]
  src/server.c
  src/server.h
  src/t_set.c
  tests/support/cluster.tcl
  tests/unit/type/set.tcl
Labels: class:feature, state:to-be-merged

#7647 Correct error message of runtest-cluster and runtest-moduleapi
  runtest-cluster
  runtest-moduleapi
Labels: class:text

#7633 Replace usage of wrongtypeerr with helper
  src/bitops.c
  src/geo.c
  src/object.c
  src/t_hash.c
  src/t_list.c
  src/t_set.c
  src/t_stream.c
  src/t_string.c
  src/t_zset.c
Labels: class:cleanup

#7588 fix misleading typo hasActiveChildProcess doc comment
  src/rax.c
  src/server.c
Labels: class:text

#1690 Add oom-score-adj configuration option to control Linux OOM killer.
  redis.conf
  src/config.c
  src/config.h
  src/replication.c
  src/server.c
  src/server.h
  tests/test_helper.tcl
  tests/unit/oom-score-adj.tcl
Labels: WAITING-OP-REPLY, state-approved, state-work-needed

#7333 wait command optimization
  src/replication.c
Labels: replication, state:to-be-merged

#6900 Annotate module API functions in redismodule.h for use with -fno-common
  src/redismodule.h
Labels: state:to-be-merged

#5794 Expands lazyfree's effort estimate to include Streams
  src/lazyfree.c
Labels: state:to-be-merged

#7696 EXEC with only read commands should not be rejected when OOM
  src/server.c
  tests/unit/multi.tcl
Labels: state:to-be-merged

#7690 Update memory metrics for INFO during loading
  src/aof.c
  src/module.c
  src/networking.c
  src/rdb.c
  src/server.c
  src/server.h
Labels: state:to-be-merged

#7644 Monotonic clock and updates to AE
  README.md
  src/Makefile
  src/ae.c
  src/ae.h
  src/fmacros.h
  src/monotonic.c
  src/monotonic.h
  src/server.c
Labels: release-notes, state:major-decision, state:to-be-merged

#6886 Optimize __ziplistCascadeUpdate algorithm
  src/ziplist.c
Labels: cpu efficiency, state:to-be-merged
