Repository redis/redis, pull requests merged in 2020-11, with the labels that each got.

#7987 Modules: Improve timer accuracy
  src/module.c
Labels: state:to-be-merged

#7957 Propagate GETSET and SET-GET as SET
  src/t_string.c
  tests/integration/replication.tcl
Labels: state:to-be-merged

#8004 Added crash report on SIGABRT
  src/debug.c
  src/redis-check-rdb.c
  src/server.c
  tests/integration/logging.tcl
Labels: state:to-be-merged

#8007 Disable rehash when redis has child process
  src/aof.c
  src/module.c
  src/rdb.c
  src/server.c
  tests/unit/other.tcl
Labels: release-notes, state:to-be-merged

#7979 Add maxclients and cluster_connections to INFO CLIENTS
  src/server.c
Labels: state:major-decision, state:needs-doc-pr, state:to-be-merged

#7994 redis-cli cluster import support source and target that need auth
  src/redis-cli.c
Labels: release-notes, state:major-decision, state:to-be-merged

#8014 rdb: corrected RedisModuleIO initialization point
  src/rdb.c
Labels: state:to-be-merged

#7982 Add RESET command.
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/other.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr

#7981 Better INFO fields to track diskless and disk-based replication progress
  src/rdb.c
  src/server.c
  src/server.h
Labels: state:major-decision, state:needs-doc-pr, state:to-be-merged

#8018 Debug Populate: Avoid server crash when passing negative value for key and value size
  src/debug.c
  src/object.c
  src/server.h
Labels: state:to-be-merged

#7995 add tracking bcast flag and client redirection in client list
  src/networking.c
Labels: state:major-decision, state:needs-doc-pr, state:to-be-merged

#7961 Add new commands ZDIFF and ZDIFFSTORE
  redis.conf
  src/db.c
  src/server.c
  src/server.h
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr

#7912 Modules callbacks for lazy free effort, and unlink
  runtest-moduleapi
  src/db.c
  src/lazyfree.c
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  src/t_set.c
  tests/modules/Makefile
  tests/modules/test_lazyfree.c
  tests/unit/moduleapi/test_lazyfree.tcl
Labels: release-notes, state:major-decision, state:to-be-merged

#7953 Add COPY command
  src/db.c
  src/server.c
  src/server.h
  src/stream.h
  src/t_hash.c
  src/t_list.c
  src/t_set.c
  src/t_stream.c
  src/t_zset.c
  tests/unit/keyspace.tcl
Labels: state:major-decision, state:needs-doc-pr

#8036 Improve and clean up supervised process support.
  redis.conf
  src/server.c
Labels: release-notes, state:major-decision

#5773 ZREVRANGEBYSCORE Optimization for out of range offset
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: cpu efficiency, state:to-be-merged

#8025 Unified MULTI, LUA, and RM_Call with respect to blocking commands
  src/aof.c
  src/module.c
  src/multi.c
  src/pubsub.c
  src/redismodule.h
  src/replication.c
  src/scripting.c
  src/server.c
  src/server.h
  src/t_list.c
  src/t_stream.c
  src/t_zset.c
  tests/modules/blockedclient.c
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/multi.tcl
  tests/unit/scripting.tcl
Labels: release-notes, state:major-decision, state:to-be-merged

#8016 EXISTS should not alter LRU, OBJECT should not reveal expired keys on replica
  src/db.c
  src/debug.c
  src/object.c
  src/server.h
  tests/unit/introspection-2.tcl
Labels: release-notes, state:major-decision, state:to-be-merged

#8061 Fix bug with module GIL being released prematurely
  src/server.c
Labels: state:to-be-merged

#7895 Fix typo in ae.c file
  src/ae.c
Labels: class:text

#7972 XPENDING with IDLE
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: release-notes, state:major-decision, state:to-be-merged
