Repository redis/redis, pull requests merged in 2020-09, with the labels that each got.

#4001 Check that THP is not set to always (madvise is ok)
  src/latency.c
Labels: safe-to-merge, state:to-be-merged

#5448 Documents RM_Call's fmt
  src/module.c
Labels: class:text, state:to-be-merged

#4341 Fix comments of _quicklistSplitNode function.
  src/quicklist.c
Labels: state:to-be-merged

#7738 RM_ThreadSafeContextTryLock a non-blocking method for acquiring GIL
  runtest-moduleapi
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/Makefile
  tests/modules/blockedclient.c
  tests/unit/moduleapi/blockedclient.tcl
Labels: state:major-decision, state:to-be-merged

#7653 Incremental eviction processing
  README.md
  redis.conf
  src/config.c
  src/evict.c
  src/networking.c
  src/server.c
  src/server.h
Labels: release-notes, state:major-decision, state:to-be-merged

#7707 Implement redisAtomic to replace _Atomic C11 builtin
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  src/Makefile
  src/atomicvar.h
  src/evict.c
  src/lazyfree.c
  src/module.c
  src/networking.c
  src/redis-benchmark.c
  src/replication.c
  src/server.c
  src/server.h
  src/zmalloc.c
Labels: release-notes, state:major-decision

#7810 debug.c: NetBSD build warning fix.
  src/debug.c
Labels: state:to-be-merged

#7804 Add Swapdb Module Event
  src/db.c
  src/module.c
  src/redismodule.h
  tests/modules/hooks.c
  tests/unit/moduleapi/hooks.tcl
Labels: state:major-decision, state:to-be-merged

#7783 RM_GetContextFlags provides indication that we're in a fork child
  src/aof.c
  src/childinfo.c
  src/module.c
  src/rdb.c
  src/redismodule.h
  src/scripting.c
  src/server.c
  src/server.h
Labels: state:major-decision, state:to-be-merged

#7789 Fix compilation warning in jemalloc's malloc_vsnprintf
  deps/jemalloc/src/malloc_io.c
Labels: state:to-be-merged

#7818 Issue 7416: Add GT and LT options to ZADD for conditional score updates
  .gitignore
  src/module.c
  src/redismodule.h
  src/server.h
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: class:feature, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7526 Stream: Inconsistency between master and replica some XREADGROUP case
  src/aof.c
  src/blocked.c
  src/rdb.c
  src/stream.h
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: state:major-decision, state:needs-doc-pr, state:to-be-merged

#7202 Don't write replies if close the client ASAP
  src/acl.c
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/acl.tcl
  tests/unit/obuf-limits.tcl
Labels: state:to-be-merged

#7293 getting rss size implementation for netbsd
  src/zmalloc.c
Labels: state:to-be-merged

#7838 warning: comparison between signed and unsigned integer in 32bit build
  src/listpack.c
Labels: state:to-be-merged

#7785 Fix compilation warnings in Lua and jemalloc dependencies
  deps/Makefile
  deps/jemalloc/configure.ac
  deps/lua/src/lauxlib.c
  deps/lua/src/ldo.c
  deps/lua/src/ltablib.c
Labels: state:to-be-merged
