Repository redis/redis, pull requests merged in 2021-09, with the labels that each got.

#9416 Fix the timing of read and write events under kqueue
  src/ae_kqueue.c
Labels: state:to-be-merged, release-notes

#9455 Fix two minor bugs (MIGRATE key args and getKeysUsingCommandTable)
  src/db.c
  src/server.c
Labels: release-notes

#9209 Add a test verifying PUBSUB NUMPAT output
  tests/unit/pubsub.tcl
Labels: release-notes

#9454 Optimize quicklistIndex to seek from the nearest end
  src/quicklist.c
  src/t_list.c
  tests/integration/corrupt-dump.tcl
Labels: state:to-be-merged, release-notes

#9448 Fix wrong offset when replica pause
  src/blocked.c
  src/networking.c
  src/server.c
  tests/unit/pause.tcl
Labels: state:to-be-merged, release-notes, approval-needed

#9446 Fix callReplyParseCollection memleak when use AutoMemory
  src/call_reply.c
  tests/modules/basics.c
Labels: state:to-be-merged

#9398 Delay to discard cached master when full synchronization
  src/replication.c
  tests/integration/replication.tcl
Labels: state:to-be-merged, release-notes, approval-needed

#9377 Add INFO total_active_defrag_time and current_active_defrag_time
  src/defrag.c
  src/server.c
  src/server.h
Labels: state:major-decision, release-notes, approval-needed

#9373 Add LMPOP/BLMPOP commands.
  src/blocked.c
  src/db.c
  src/module.c
  src/server.c
  src/server.h
  src/t_list.c
  src/t_stream.c
  src/t_zset.c
  tests/integration/aof.tcl
  tests/unit/type/list.tcl
Labels: state:major-decision, release-notes, approval-needed

#9449 [lua] Use all characters to calculate string hash
  deps/lua/src/lstring.c
Labels: state:to-be-merged, release-notes

#9477 Fix: client pause uses an old timeout
  src/networking.c
  src/server.c
Labels: state:to-be-merged, release-notes

#9330 Remove redundant validation and prevent duplicate users during ACL load
  src/acl.c
  tests/unit/acl.tcl
Labels: state:to-be-merged, state:major-decision, release-notes, breaking-change

#9366 Replace all usage of ziplist with listpack for t_zset
  redis.conf
  src/aof.c
  src/config.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/geo.c
  src/listpack.c
  src/listpack.h
  src/module.c
  src/object.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/server.h
  src/t_hash.c
  src/t_zset.c
  src/ziplist.c
  src/ziplist.h
  tests/assets/corrupt_empty_keys.rdb
  tests/assets/zset-ziplist.rdb
  tests/integration/convert-ziplist-zset-on-load.tcl
  tests/integration/corrupt-dump.tcl
  tests/test_helper.tcl
  tests/unit/aofrw.tcl
  tests/unit/keyspace.tcl
  tests/unit/scan.tcl
  tests/unit/type/zset.tcl
Labels: state:to-be-merged

#9324 bitpos/bitcount add bit index
  src/bitops.c
  tests/support/util.tcl
  tests/unit/bitops.tcl
Labels: state:needs-doc-pr, state:to-be-merged, state:major-decision, release-notes, approval-needed

#8015 PSYNC2: make partial sync possible after master reboot
  src/rdb.c
  src/rdb.h
  src/server.c
  src/server.h
  tests/integration/psync2-master-restart.tcl
  tests/integration/rdb.tcl
  tests/test_helper.tcl
Labels: state:to-be-merged, state:major-decision, release-notes

#8439 Modules: Add remaining list API functions
  runtest-moduleapi
  src/module.c
  src/quicklist.c
  src/quicklist.h
  src/redismodule.h
  src/server.h
  src/t_list.c
  tests/modules/Makefile
  tests/modules/list.c
  tests/unit/moduleapi/list.tcl
Labels: state:major-decision, release-notes, approval-needed

#9314 Added URI support to redis-benchmark (cli and benchmark share the same uri-parsing methods)
  src/cli_common.c
  src/cli_common.h
  src/redis-benchmark.c
  src/redis-cli.c
  tests/integration/redis-benchmark.tcl
  tests/support/benchmark.tcl
Labels: state:to-be-merged, release-notes

#8324 A better approach for COMMAND INFO for movablekeys commands
  runtest-moduleapi
  src/acl.c
  src/db.c
  src/module.c
  src/redismodule.h
  src/sentinel.c
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/keyspecs.c
  tests/unit/moduleapi/keyspecs.tcl
Labels: state:needs-doc-pr, state:to-be-merged, state:major-decision, release-notes, approval-needed

#9425 Adds limit to SINTERCARD/ZINTERCARD.
  src/db.c
  src/server.c
  src/server.h
  src/t_set.c
  src/t_zset.c
  tests/unit/type/set.tcl
  tests/unit/type/zset.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#9513 fix replication test failure, probing the wrong log file
  tests/integration/replication.tcl
Labels: state:to-be-merged

#9508 CLIENT LIST / INFO show resp version
  src/networking.c
Labels: state:to-be-merged, state:major-decision, release-notes, approval-needed

#9527 tune lazyfree test timeout
  tests/unit/lazyfree.tcl
Labels: state:to-be-merged

#9484 Add ZMPOP/BZMPOP commands.
  src/blocked.c
  src/db.c
  src/server.c
  src/server.h
  src/t_list.c
  src/t_zset.c
  tests/integration/aof.tcl
  tests/unit/type/list.tcl
  tests/unit/type/zset.tcl
Labels: state:needs-doc-pr, state:to-be-merged, state:major-decision, release-notes, approval-needed

#9309 Adding ACL support for modules
  runtest-moduleapi
  src/acl.c
  src/module.c
  src/multi.c
  src/redismodule.h
  src/scripting.c
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/aclcheck.c
  tests/unit/moduleapi/aclcheck.tcl
Labels: state:to-be-merged, state:major-decision, release-notes, approval-needed

#8687 Client eviction
  redis.conf
  src/blocked.c
  src/config.c
  src/debug.c
  src/multi.c
  src/networking.c
  src/object.c
  src/pubsub.c
  src/redis-cli.c
  src/replication.c
  src/server.c
  src/server.h
  src/tracking.c
  src/util.c
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/client-eviction.tcl
  tests/unit/maxmemory.tcl
Labels: state:needs-design, state:needs-doc-pr, state:to-be-merged, state:major-decision, release-notes, approval-needed

#9540 Add RM_TrimStringAllocation().
  src/module.c
  src/redismodule.h
  tests/modules/basics.c
Labels: state:major-decision, release-notes, approval-needed

#9533 Minor optimize getMaxmemoryState, when server.maxmemory is not set
  src/evict.c
Labels: state:to-be-merged

#9538 Use dictGetFairRandomKey() for HRANDFIELD,SRANDMEMBER,ZRANDMEMBER
  src/t_hash.c
  src/t_set.c
  src/t_zset.c
Labels: state:to-be-merged

#9510 Fix obtain the AOF file length error when load AOF
  src/aof.c
Labels: state:to-be-merged

#9553 Fix stream sanitization for non-int first value
  src/t_stream.c
  tests/integration/rdb.tcl
Labels: state:to-be-merged

#9541 Use __common__ attribute in redismodule.h for Clang C builds
  src/redismodule.h
Labels: state:to-be-merged

#9537 Modules: add RM_LoadDataTypeFromStringEncver
  src/module.c
  src/redismodule.h
  tests/modules/datatype.c
  tests/unit/moduleapi/datatype.tcl
Labels: state:to-be-merged, release-notes, approval-needed

#9519 Fix error message for replica-serve-stale-data in redis.conf doc
  redis.conf
Labels: state:to-be-merged
