Repository redis/redis, pull requests merged in 2021-12, with the labels that each got.

#9748 Multiparam config set
  redis.conf
  src/config.c
  src/replication.c
  src/server.c
  src/server.h
  src/tls.c
  tests/unit/introspection.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-not-after-rc1

#9780 Redis Function
  README.md
  src/Makefile
  src/acl.c
  src/aof.c
  src/config.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/eval.c
  src/evict.c
  src/function_lua.c
  src/functions.c
  src/functions.h
  src/module.c
  src/networking.c
  src/object.c
  src/rdb.c
  src/rdb.h
  src/replication.c
  src/script.c
  src/script.h
  src/script_lua.c
  src/script_lua.h
  src/scripting.c
  src/server.c
  src/server.h
  src/sort.c
  src/t_stream.c
  tests/integration/replication.tcl
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#9910 Fix timing issue in logging.tcl with FreeBSD
  tests/integration/logging.tcl
Labels: state:to-be-merged

#9896 Fix outdated protected-mode documentation in sentinel.conf
  sentinel.conf
Labels: state:to-be-merged

#9888 Hide hidden configs from `config get` patterns.
  src/config.c
  tests/unit/introspection.tcl
Labels: 7.0-not-after-rc1

#9927 Fix timing issue in strem blocking tests
  tests/unit/type/stream.tcl
Labels: state:to-be-merged

#9916 Fix possible int overflow when hashing an sds.
  src/dict.c
  src/dict.h
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/type/list.tcl
  tests/unit/type/set.tcl
  tests/unit/violations.tcl
Labels: release-notes

#9826 Throw error on too long unix domain socket file path
  src/anet.c
  src/server.c
Labels: state:to-be-merged

#9914 Multiparam config get. See #9871.
  src/commands.c
  src/commands/config-get.json
  src/config.c
  tests/unit/introspection.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-not-after-rc1

#9936 Add FUNCTION FLUSH command to flush all functions
  src/commands.c
  src/commands/function-flush.json
  src/functions.c
  src/functions.h
  src/lazyfree.c
  src/server.h
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/functions.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#9774 Introduce memory management on cluster link buffers
  redis.conf
  src/cluster.c
  src/cluster.h
  src/commands.c
  src/commands/cluster-links.json
  src/config.c
  src/object.c
  src/server.c
  src/server.h
  tests/cluster/cluster.tcl
  tests/cluster/tests/24-links.tcl
  tests/support/util.tcl
  tests/unit/pendingquerybuf.tcl
Labels: state:needs-code-doc, state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#9920 Protected configs and sensitive commands
  .github/workflows/external.yml
  redis.conf
  src/commands.c
  src/commands/debug.json
  src/commands/module-load.json
  src/commands/module-unload.json
  src/config.c
  src/networking.c
  src/server.c
  src/server.h
  tests/assets/default.conf
  tests/support/util.tcl
  tests/unit/introspection.tcl
  tests/unit/moduleapi/basics.tcl
  tests/unit/networking.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change, 7.0-not-after-rc1

#9962 Fix some nonsense came from LGTM
  src/anet.c
  src/dict.c
  src/geo.c
  src/quicklist.h
  src/redis-cli.c
Labels: state:to-be-merged

#9812 Remove EVAL script verbatim replication, propagation, and deterministic execution logic
  src/aof.c
  src/commands.c
  src/commands/script-flush.json
  src/commands/script-load.json
  src/config.c
  src/debug.c
  src/defrag.c
  src/eval.c
  src/object.c
  src/rdb.c
  src/replication.c
  src/script.c
  src/script.h
  src/script_lua.c
  src/server.c
  src/server.h
  tests/assets/scriptbackup.rdb
  tests/integration/aof.tcl
  tests/integration/psync2.tcl
  tests/integration/rdb.tcl
  tests/integration/replication-3.tcl
  tests/unit/multi.tcl
  tests/unit/pause.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change, 7.0-must-have

#9953 Change FUNCTION CREATE, DELETE and FLUSH to be WRITE commands instead of MAY_REPLICATE.
  src/cluster.c
  src/commands.c
  src/commands/cluster-reset.json
  src/commands/function-create.json
  src/commands/function-delete.json
  src/commands/function-flush.json
  src/commands/function-info.json
  src/commands/function-kill.json
  src/commands/function-list.json
  src/commands/function-stats.json
  src/db.c
  src/debug.c
  src/functions.c
  src/functions.h
  src/rdb.c
  src/replication.c
  src/server.h
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, approval-needed, 7.0-must-have

#4909 There is mismach between function sdssplitlen() comments and implementation
  src/sds.c
Labels: state:to-be-merged

#9878 Allow most CONFIG SET during loading, block some commands in async-loading
  src/commands.c
  src/commands/bgrewriteaof.json
  src/commands/bgsave.json
  src/commands/cluster-addslots.json
  src/commands/cluster-addslotsrange.json
  src/commands/cluster-bumpepoch.json
  src/commands/cluster-delslots.json
  src/commands/cluster-delslotsrange.json
  src/commands/cluster-failover.json
  src/commands/cluster-flushslots.json
  src/commands/cluster-forget.json
  src/commands/cluster-meet.json
  src/commands/cluster-replicate.json
  src/commands/cluster-saveconfig.json
  src/commands/cluster-set-config-epoch.json
  src/commands/cluster-setslot.json
  src/commands/config-resetstat.json
  src/commands/config-rewrite.json
  src/commands/config-set.json
  src/commands/module-load.json
  src/commands/module-unload.json
  src/commands/psync.json
  src/commands/replicaof.json
  src/commands/save.json
  src/commands/slaveof.json
  src/commands/sync.json
  src/config.c
  src/networking.c
  src/server.c
  src/server.h
  tests/integration/replication.tcl
  tests/unit/introspection.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#9890 Sort out mess around propagation and MULTI/EXEC
  src/aof.c
  src/blocked.c
  src/config.c
  src/db.c
  src/evict.c
  src/expire.c
  src/module.c
  src/multi.c
  src/networking.c
  src/replication.c
  src/script.c
  src/script.h
  src/server.c
  src/server.h
  src/t_list.c
  src/t_stream.c
  tests/modules/propagate.c
  tests/unit/maxmemory.tcl
  tests/unit/moduleapi/propagate.tcl
  tests/unit/moduleapi/test_lazyfree.tcl
  tests/unit/multi.tcl
  tests/unit/scripting.tcl
  tests/unit/type/list.tcl
Labels: state:major-decision, approval-needed, 7.0-not-after-rc1

#9954 redis-cli: Add OUTPUT_JSON format type
  src/redis-cli.c
Labels: state:major-decision, class:feature, release-notes, approval-needed

#9938 Add FUNCTION DUMP and RESTORE.
  src/cluster.c
  src/commands.c
  src/commands/function-dump.json
  src/commands/function-restore.json
  src/functions.c
  src/rdb.c
  src/rdb.h
  src/redis-cli.c
  src/server.h
  tests/unit/cluster.tcl
  tests/unit/functions.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10002 santize dump payload: fix carsh when zset with NAN score
  src/rdb.c
  tests/integration/corrupt-dump.tcl
Labels: state:to-be-merged

#10010 Tests: don't rely on the response of MEMORY USAGE when mem_allocator is not jemalloc
  tests/support/util.tcl
  tests/unit/moduleapi/datatype2.tcl
  tests/unit/type/hash.tcl
Labels: state:to-be-merged

#9972 check somaxconn system settings on macOS, FreeBSD and OpenBSD.
  src/config.h
  src/server.c
Labels: release-notes

#10003 Safe and organized exit when receiving sigterm while loading
  src/server.c
Labels: release-notes

#9980 redis-cli: Add -X option and extend --cluster call take arg from stdin
  src/redis-cli.c
  tests/integration/redis-cli.tcl
Labels: state:major-decision, release-notes, approval-needed

#9983 Modules: Mark APIs non-experimental
  src/redismodule.h
  tests/modules/aclcheck.c
  tests/modules/auth.c
  tests/modules/basics.c
  tests/modules/blockedclient.c
  tests/modules/blockonbackground.c
  tests/modules/blockonkeys.c
  tests/modules/commandfilter.c
  tests/modules/defragtest.c
  tests/modules/fork.c
  tests/modules/getkeys.c
  tests/modules/keyspace_events.c
  tests/modules/misc.c
  tests/modules/propagate.c
  tests/modules/timer.c
Labels: state:major-decision, approval-needed

#10022 Constrain node ID logging when exceeding send buffer limit
  src/cluster.c
Labels: state:to-be-merged
