Repository redis/redis, pull requests merged in 2021-05, with the labels that each got.

#8853 Fix memory leak in moduleDefragGlobals
  src/module.c
Labels: release-notes, state:to-be-merged

#8901 Free value if dup succeed but listAddNodeTail failed.
  src/adlist.c
Labels: state:to-be-merged

#8899 Fix typos in comments and improve their readability
  src/cluster.c
  src/module.c
Labels: class:text

#8833 Enforce client output buffer soft limit when no traffic.
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/obuf-limits.tcl
Labels: release-notes, state:to-be-merged

#8916 fix redis-benchmark to ignore unsupported configs
  src/redis-benchmark.c
Labels: state:to-be-merged

#8898 redis-cli when SELECT fails, we should reset dbnum to 0
  src/redis-cli.c
Labels: state:to-be-merged

#8931 redis-benchmark bad check for NOAUTH and NOPERM
  src/redis-benchmark.c
Labels: state:to-be-merged

#8932 Fix crash unlinking a stream with groups rax and no groups
  src/lazyfree.c
Labels: release-notes, state:to-be-merged

#8856 cluster process publish message only when know that node.
  src/cluster.c
Labels: state:to-be-merged

#8678 improve error handing in anetFDToString to avoid returning successfully with garbage.
  src/anet.c
Labels: state:to-be-merged

#8820 EVALSHA_RO and EVAL_RO Commands
  src/scripting.c
  src/server.c
  src/server.h
  tests/unit/scripting.tcl
Labels: approval-needed, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8949 sinterstore: add missing keyspace del event when any source set not exists.
  src/t_set.c
Labels: release-notes

#8914 redis-cli: fix bugs in hints of commands with subcommands.
  src/redis-cli.c
Labels: state:needs-review, state:to-be-merged

#8934 Reset lazyfreed_objects info field with RESETSTAT, test for stream lazyfree
  src/lazyfree.c
  src/server.c
  src/server.h
  tests/unit/lazyfree.tcl
Labels: state:major-decision, state:to-be-merged

#5362 AOF: remove memmove in aofChildWriteDiffData and record the latency
  src/aof.c
Labels: state:to-be-merged

#8884 redis-cli: Sleep for a while in each cliConnect when we got connect error in cluster mode.
  src/redis-cli.c
Labels: state:to-be-merged

#8895 redis-cli: some commands should bypass history file.
  src/redis-cli.c
Labels: release-notes, state:to-be-merged

#8960 fix race in config rewrite test
  tests/unit/introspection.tcl
Labels: state:to-be-merged

#8939 Remove useless - from help.h on commands with no arguments
  src/help.h
  utils/generate-command-help.rb
Labels: state:to-be-merged

#8963 longer timeout in replication test
  tests/integration/replication.tcl
Labels: state:to-be-merged

#8883 Add documentation for `firstkey`, `lastkey` and `keystep` parameters of `RedisModule_CreateCommand`
  src/module.c
Labels: class:text, state:to-be-merged

#8926 try a more concise rdbTryIntegerEncoding
  src/rdb.c
Labels: state:to-be-merged

#8965 Fix race in new lazyfree test
  tests/unit/lazyfree.tcl
Labels: state:to-be-merged

#8859 Hide migrate command from slowlog if they include auth
  src/acl.c
  src/cluster.c
  src/config.c
  src/multi.c
  src/networking.c
  src/replication.c
  src/scripting.c
  src/server.c
  src/server.h
  tests/unit/introspection.tcl
  tests/unit/other.tcl
  tests/unit/slowlog.tcl
Labels: approval-needed, release-notes, state:major-decision

#8966 Make full use of replication backlog memory
  src/config.c
  src/replication.c
  src/server.h
Labels: state:to-be-merged

#8970 Count zmalloc size of aof buf into overhead
  src/evict.c
Labels: state:to-be-merged

#8958 [SENTINEL] reset sentinel-user/pass to NULL when user config with empty string
  src/sentinel.c
Labels: release-notes, state:to-be-merged

#8991 unregister AE_READABLE from the read pipe in backgroundSaveDoneHandle…
  src/rdb.c
  tests/integration/replication.tcl
Labels: release-notes, state:to-be-merged

#8474 Always replicate TTLs as absolute timestamps in milliseconds
  src/aof.c
  src/cluster.c
  src/expire.c
  src/server.c
  src/server.h
  src/t_string.c
  tests/cluster/tests/14-consistency-check.tcl
  tests/integration/aof.tcl
  tests/support/util.tcl
  tests/unit/expire.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8975 Make full use of aofrwblock's buf
  src/aof.c
  src/evict.c
  src/object.c
  src/server.h
Labels: state:to-be-merged

#8969 Extend freeSlotsToKeysMapAsync and freeTrackingRadixTreeAsync to check LAZYFREE_THRESHOLD.
  src/lazyfree.c
Labels: state:to-be-merged
