Repository redis/redis, pull requests merged in 2021-06, with the labels that each got.

#9010 Improve new time sensitive pexpireat propagation test
  tests/unit/expire.tcl
Labels: state:to-be-merged

#8945 redis-cli cluster import command may issue wrong MIGRATE command.
  src/redis-cli.c
Labels: class:bug, release-notes

#9042 tests: add details when test fails on malformed info
  tests/integration/redis-cli.tcl
Labels: state:to-be-merged

#9047 XTRIM call streamParseAddOrTrimArgsOrReply use wrong arg xadd.
  src/t_stream.c
Labels: state:to-be-merged

#8921 comment typo: form -> from
  src/hyperloglog.c
Labels: state:to-be-merged

#9048 Fix XTRIM or XADD with LIMIT may delete more entries than Count.
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: release-notes, state:to-be-merged

#8906 Add support for combining NX and GET flags on SET command
  src/t_string.c
  tests/unit/type/string.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#9013 Make redis-cli grep friendly in pubsub mode.
  src/redis-cli.c
Labels: state:to-be-merged

#8968 Mem efficiency, make full use of client struct memory for reply buffers
  README.md
  src/aof.c
  src/networking.c
  src/scripting.c
  src/server.h
Labels: release-notes, state:to-be-merged

#9032 Fix accidental deletion of sinterstore command when we meet wrong type error.
  src/t_set.c
  tests/unit/type/set.tcl
Labels: release-notes, state:major-decision, state:needs-test-code

#9061 msetnx reply error
  src/t_string.c
Labels: state:to-be-merged

#9012 cleanup around loadAppendOnlyFile
  src/aof.c
  src/debug.c
  src/server.c
  src/server.h
  tests/integration/aof.tcl
Labels: state:to-be-merged

#9018 slowlog get command supports passing in -1 to get all logs.
  src/slowlog.c
  tests/unit/slowlog.tcl
Labels: approval-needed, state:major-decision, state:to-be-merged

#9041 Fix coredump after Client Unpause command when threaded I/O is enabled
  src/networking.c
Labels: release-notes, state:to-be-merged

#8943 presize hashtable to avoid rehashing in hashTypeConvertZiplist()
  src/t_hash.c
Labels: class:optimization

#9086 Check `CLIENT_DIRTY_CAS` flag before process transaction.
  src/multi.c
Labels: state:to-be-merged

#9003 Fix the wrong reisze of querybuf
  src/networking.c
  src/sds.c
  src/sds.h
  src/server.c
  src/server.h
  tests/test_helper.tcl
  tests/unit/maxmemory.tcl
  tests/unit/querybuf.tcl
Labels: state:to-be-merged

#8981 Change return value type for ZPOPMAX/MIN in RESP3
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8999 Enhance mem_usage/free_effort/unlink/copy callbacks and add GetDbFromIO Api.
  runtest-moduleapi
  src/aof.c
  src/cluster.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/lazyfree.c
  src/module.c
  src/object.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/redismodule.h
  src/server.h
  src/t_set.c
  tests/modules/Makefile
  tests/modules/datatype2.c
  tests/modules/defragtest.c
  tests/unit/moduleapi/datatype2.tcl
Labels: approval-needed, release-notes, state:major-decision

#9057 Remove gopher protocol support.
  redis.conf
  src/Makefile
  src/config.c
  src/gopher.c
  src/networking.c
  src/server.h
Labels: approval-needed, release-notes, state:major-decision

#8980 Support glob pattern matching for config include files
  redis.conf
  src/config.c
Labels: approval-needed, release-notes, state:major-decision

#9095 Improve objectComputeSize() with allocator fragmentaiton.
  src/object.c
Labels: release-notes

#6741 create the log file only after done parsing the entire config file
  src/config.c
Labels: approval-needed, operations, release-notes, state:to-be-merged

#7338 redis-cli: support for REDIS_REPLY_SET in CSV and RAW output.
  src/redis-cli.c
Labels: release-notes

#9116 Fix race in client side tracking
  src/tracking.c
  tests/unit/tracking.tcl
Labels: release-notes, state:to-be-merged

#9000 [sentinel] add tilt mode since in sentinel info
  src/sentinel.c
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#9121 solve test timing issues in replication tests
  tests/integration/rdb.tcl
  tests/integration/replication-3.tcl
  tests/integration/replication.tcl
Labels: state:to-be-merged

#3718 modules: Add newlen == 0 handling to RM_StringTruncate (#3717)
  runtest-moduleapi
  src/Makefile
  src/module.c
  tests/modules/Makefile
  tests/modules/basics.c
  tests/unit/moduleapi/basics.tcl
Labels: release-notes, state:to-be-merged

#9034 Improve bind and protected-mode config handling.
  src/cluster.c
  src/config.c
  src/networking.c
  src/server.c
  src/server.h
  tests/support/cli.tcl
  tests/support/server.tcl
  tests/unit/networking.tcl
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#9125 Adjustments to recent RM_StringTruncate fix (#3718)
  src/module.c
  src/sds.c
  src/sds.h
  tests/modules/basics.c
Labels: state:to-be-merged

#9140 Fix failing basics moduleapi test on 32bit CI
  tests/modules/basics.c
  tests/unit/moduleapi/basics.tcl
Labels: state:to-be-merged

#9141 Re-fix daily CI
  .github/workflows/daily.yml
Labels: state:to-be-merged

#9142 Add bind-source-addr configuration argument.
  redis.conf
  src/cluster.c
  src/config.c
  src/replication.c
  src/sentinel.c
  src/server.c
  src/server.h
  tests/unit/networking.tcl
Labels: approval-needed, release-notes, state:major-decision

#9162 ZRANDMEMBER WITHSCORES with negative COUNT may return bad score
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: release-notes, state:to-be-merged

#9165 Improve doc comment about AE_DONT_WAIT
  src/ae.c
Labels: class:text, state:to-be-merged

#9089 fix ZRANGESTORE - should return 0 when src points to an empty key
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: approval-needed, release-notes, state:to-be-merged

#9115 Simplify logic in raxSeek, eliminate it->key reassembly on gt and lt
  src/rax.c
Labels: state:to-be-merged

#9159 Fix timing issue in psync2 test.
  tests/integration/psync2.tcl
Labels: state:to-be-merged

#4615 HSETNX can lead coding type change even when skipped due to NX
  src/t_hash.c
Labels: state:to-be-merged

#9158 Add missing pause tcl test to test_helper.tcl
  tests/test_helper.tcl
  tests/unit/pause.tcl
Labels: state:to-be-merged

#9124 Make redis-cli --help/-h output to stdout and exit with 0.
  src/redis-cli.c
Labels: state:to-be-merged

#2080 Fix ziplist length updates on bigendian platforms
  src/ziplist.c
Labels: release-notes

#9135 redis-cli --rdb: fix broken fsync/ftruncate for stdout
  src/redis-cli.c
Labels: release-notes, state:to-be-merged
