Repository redis/redis, pull requests merged in 2021-11, with the labels that each got.

#4326 Remove duplicate SET_OP_XX definitions in t_set.c.
  src/t_set.c
Labels: state:to-be-merged

#9733 Fix COMMAND GETKEYS on EVAL without keys
  src/module.c
  src/server.c
  src/server.h
  tests/unit/introspection-2.tcl
Labels: release-notes

#9357 Add support for list type to store elements larger than 4GB
  .github/workflows/daily.yml
  src/debug.c
  src/defrag.c
  src/object.c
  src/quicklist.c
  src/quicklist.h
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/t_list.c
  tests/README.md
  tests/assets/list-quicklist.rdb
  tests/integration/corrupt-dump.tcl
  tests/integration/rdb.tcl
  tests/support/redis.tcl
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/type/list.tcl
Labels: state:major-decision, release-notes, approval-needed

#9629 Retry when a blocked connection system call is interrupted by a signal
  src/connection.h
  src/rio.c
  tests/integration/replication.tcl
Labels: state:to-be-merged

#9692 Fixes LPOP/RPOP wrong replies when count is 0
  src/t_list.c
  tests/unit/type/list.tcl
Labels: state:needs-doc-pr, release-notes, breaking-change

#9323 Replica keep serving data during repl-diskless-load=swapdb for better availability
  redis.conf
  src/aof.c
  src/cluster.c
  src/cluster.h
  src/db.c
  src/defrag.c
  src/module.c
  src/multi.c
  src/rdb.c
  src/rdb.h
  src/redismodule.h
  src/replication.c
  src/scripting.c
  src/server.c
  src/server.h
  tests/cluster/tests/17-diskless-load-swapdb.tcl
  tests/cluster/tests/includes/init-tests.tcl
  tests/integration/replication.tcl
  tests/modules/testrdb.c
  tests/unit/moduleapi/testrdb.tcl
Labels: state:to-be-merged, state:major-decision, release-notes, approval-needed, 7.0-not-after-rc1

#9644 Refactor config.c for generic setter interface
  src/config.c
  src/debug.c
  src/server.c
  src/server.h
Labels: state:major-decision, approval-needed, 7.0-not-after-rc1

#9753 Sentinel tls memory leak
  src/sentinel.c
Labels: release-notes

#9601 Add sanitizer support and clean up sanitizer findings
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  src/Makefile
  src/aof.c
  src/bitops.c
  src/cli_common.c
  src/cluster.c
  src/config.c
  src/config.h
  src/debug.c
  src/dict.c
  src/dict.h
  src/expire.c
  src/hyperloglog.c
  src/lzf_c.c
  src/memtest.c
  src/networking.c
  src/quicklist.c
  src/rax.c
  src/rdb.c
  src/redisassert.c
  src/sentinel.c
  src/sha256.c
  src/siphash.c
  src/ziplist.c
  tests/instances.tcl
  tests/integration/logging.tcl
  tests/support/server.tcl
  tests/support/util.tcl
Labels: state:to-be-merged

#9776 Change lzf to handle values larger than UINT32_MAX
  src/lzf.h
  src/lzfP.h
  src/lzf_c.c
  src/lzf_d.c
  src/quicklist.c
  tests/unit/bitops.tcl
Labels: release-notes

#5606 [Bug Fix] Set aof rewrite status err when fork failed
  src/aof.c
Labels: state:to-be-merged

#9676 Unpause clients after manual failover ends instead of the timed offset
  src/cluster.c
Labels: release-notes

#9711 Fixes ZPOPMIN/ZPOPMAX wrong replies when count is 0 with non-zset
  src/blocked.c
  src/module.c
  src/server.h
  src/t_list.c
  src/t_stream.c
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: state:to-be-merged, release-notes, breaking-change

#9799 Obliterate STRALGO! add LCS (which only works on keys)
  src/server.c
  src/server.h
  src/t_string.c
  tests/support/util.tcl
  tests/unit/type/string.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change

#9757 Reject PING with MASTERDOWN when replica-serve-stale-data=no
  redis.conf
  src/server.c
  tests/unit/multi.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change

#9778 Improve active defrag in jemalloc 5.2
  deps/jemalloc/include/jemalloc/internal/jemalloc_internal_inlines_c.h
  tests/unit/memefficiency.tcl
Labels: 7.0-must-have

#9817 Prevent LCS from allocating temp memory over proto-max-bulk-len
  src/t_string.c
  tests/integration/corrupt-dump.tcl
Labels: release-notes

#9798 QUIT is a command, HOST: and POST are not
  src/networking.c
  src/server.c
  src/server.h
  tests/modules/misc.c
  tests/unit/info.tcl
  tests/unit/moduleapi/misc.tcl
Labels: release-notes, approval-needed

#9839 Add tests to cover EXPIRE overflow detection fix
  tests/unit/expire.tcl
Labels: release-notes

#9740 Replace ziplist with listpack in quicklist
  redis.conf
  src/config.c
  src/db.c
  src/debug.c
  src/listpack.c
  src/listpack.h
  src/module.c
  src/object.c
  src/quicklist.c
  src/quicklist.h
  src/rdb.c
  src/server.c
  src/server.h
  src/t_list.c
  src/t_zset.c
  src/util.c
  tests/integration/corrupt-dump.tcl
Labels: state:major-decision, release-notes, approval-needed

#9572 Sort out the mess around writable replicas and lookupKeyRead/Write
  src/aof.c
  src/blocked.c
  src/cluster.c
  src/db.c
  src/hyperloglog.c
  src/server.h
  src/sort.c
  src/t_set.c
  src/t_zset.c
  tests/integration/replication-3.tcl
  tests/integration/replication-4.tcl
  tests/modules/aclcheck.c
  tests/modules/basics.c
  tests/modules/blockedclient.c
  tests/modules/blockonkeys.c
  tests/modules/datatype.c
  tests/modules/hash.c
  tests/modules/keyspace_events.c
  tests/modules/list.c
  tests/modules/propagate.c
  tests/modules/stream.c
  tests/modules/test_lazyfree.c
  tests/modules/testrdb.c
  tests/modules/zset.c
  tests/unit/type/list.tcl
Labels: release-notes, breaking-change, 7.0-must-have

#9849 Fix abnormal compression due to out-of-control recompress
  src/quicklist.c
  src/quicklist.h
  src/t_list.c
  tests/unit/type/list-3.tcl
Labels: release-notes

#9853 Fix CLIENT KILL kill all clients with id 0
  src/networking.c
  tests/unit/introspection.tcl
Labels: state:to-be-merged, release-notes

#9438 Sentinel master reboot fix
  sentinel.conf
  src/sentinel.c
  tests/sentinel/tests/12-master-reboot.tcl
Labels: state:to-be-merged, release-notes

#9217 Adds auto-seq-only-generation via `XADD ... <ms>-*`
  src/module.c
  src/stream.h
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: state:major-decision, 7.0-not-after-rc1
