Repository redis/redis, pull requests merged in 2021-04, with the labels that each got.

#8709 Use chi-square for random distributivity verification in test
  tests/support/util.tcl
  tests/unit/type/hash.tcl
  tests/unit/type/set.tcl
  tests/unit/type/zset.tcl
Labels: state:to-be-merged

#4246 Added macros for RM_log logging levels
  src/module.c
  src/redismodule.h
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8714 reuse existing range comparators in zslDeleteRangeByScore
  src/t_zset.c
Labels: state:to-be-merged

#8730 generalize config file check for sentinel
  src/sentinel.c
  src/server.c
  src/server.h
Labels: state:to-be-merged

#8717 zsetAdd: Fix wrong reply in case of INCR and GT/LT
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: approval-needed, release-notes

#8728 Solve sentinel test issue in TLS due to recent tests change.
  tests/instances.tcl
  tests/sentinel/tests/00-base.tcl
  tests/sentinel/tests/01-conf-update.tcl
  tests/sentinel/tests/02-slaves-reconf.tcl
  tests/sentinel/tests/05-manual.tcl
Labels: state:to-be-merged

#8725 Fix XAUTOCLAIM response to return the next available id as the cursor
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: release-notes

#8419 Handle remaining fsync errors
  src/aof.c
  src/bio.c
  src/cluster.c
  src/redis-cli.c
  src/rio.c
  src/server.c
  src/server.h
Labels: release-notes, state:to-be-merged

#8723 Fix "default" user will not have channels permissions by default.
  src/acl.c
  src/config.c
  src/server.h
  tests/assets/user.acl
  tests/unit/acl.tcl
Labels: approval-needed, release-notes, state:major-decision

#8670 Fix: server will crash if rdbload or rdbsave method is not provided in module
  src/module.c
  tests/modules/datatype.c
  tests/modules/defragtest.c
  tests/modules/testrdb.c
Labels: state:to-be-merged

#8746 Fix out of range confusing error messages (XAUTOCLAIM, RPOP count)
  src/object.c
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: state:to-be-merged

#8764 Fix busy loop in ae.c when timer event is about to fire
  src/ae.c
  src/ae_epoll.c
Labels: release-notes

#8770 Add more attempts to a timing sensitive test
  tests/unit/expire.tcl
Labels: state:to-be-merged

#8762 Add a timeout mechanism for replicas stuck in fullsync
  src/networking.c
  src/replication.c
  src/server.h
  tests/integration/replication.tcl
Labels: release-notes

#8805 Improve testsuite print of log file
  tests/support/server.tcl
  tests/support/test.tcl
  tests/support/util.tcl
Labels: state:to-be-merged

#8807 Fix timing of new replication test
  tests/integration/replication.tcl
Labels: state:to-be-merged

#8785 fix invalid master_link_down_since_seconds in info repication
  src/replication.c
  src/server.c
Labels: release-notes, state:to-be-merged

#8803 Fix ouput buffer limit test
  tests/unit/obuf-limits.tcl
Labels: state:to-be-merged

#8794 ACL channels permission handling for save/load scenario.
  redis.conf
  src/acl.c
  tests/assets/nodefaultuser.acl
  tests/unit/acl.tcl
Labels: release-notes

#8822 Fix memory leak when doing lazy free of the tracking table
  src/lazyfree.c
  src/server.h
  tests/unit/tracking.tcl
Labels: release-notes, state:to-be-merged

#8815 Fix migrateCommand may migrate wrong value.
  src/cluster.c
Labels: state:to-be-merged

#8823 Print the number of abnormal line in AOF
  src/redis-check-aof.c
  tests/integration/aof.tcl
Labels: state:to-be-merged

#8772 Fix typo in redis-cli.c
  src/redis-cli.c
Labels: class:text

#8834 Fix typo and (hopefully) slightly improve comment readability
  src/module.c
Labels: class:text

#8827 Fix typo in rdb.c
  src/rdb.c
Labels: class:text

#8809 Fix typo in server.c
  src/server.c
Labels: class:text

#8707 Update redis conf
  redis.conf
Labels: class:text

#8830 Expire key firstly and then notify keyspace event
  src/db.c
Labels: state:to-be-merged

#8812 Use monotonic clock to check for Lua script timeout.
  src/db.c
  src/scripting.c
  src/server.h
Labels: release-notes, state:to-be-merged

#8843 change http to https in readme
  README.md
Labels: class:text

#8845 Fix comment
  src/sentinel.c
Labels: class:text

#8837 fuzz tester, try to print hung command
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  tests/integration/corrupt-dump-fuzzer.tcl
  tests/support/util.tcl
Labels: state:to-be-merged

#8801 Fix comments and typo in many places.
  sentinel.conf
  src/cluster.c
  src/replication.c
  src/sentinel.c
Labels: class:text

#8854 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: state:to-be-merged

#8873 GEOSEARCHSTORE: removed unsupported args from comment
  src/geo.c
Labels: class:text

#8874 Fix some typos in the code of basic data structures
  src/t_hash.c
  src/t_list.c
  src/t_stream.c
  src/t_string.c
Labels: class:text

#8875 When test CONFIG bind with non valid address, some server may configure search domain.
  tests/unit/networking.tcl
Labels: state:to-be-merged

#8870 redis-cli: Do not use hostsocket when we got redirected in cluster mode
  src/redis-cli.c
Labels: state:to-be-merged

#8872 redis-benchmark: Add zfree(data) and fix lrange size / text mismatch
  src/redis-benchmark.c
Labels: state:to-be-merged

#8879 Improve redis-cli help
  src/redis-cli.c
Labels: state:to-be-merged
