Repository redis/redis, pull requests merged in 2021-02, with the labels that each got.

#8431 Cleanup: addReplyAggregateLen and addReplyBulkLen remove redundant check
  src/networking.c
Labels: state:to-be-merged

#8326 Optimizing sorted GEORADIUS COUNT with partial sorting.
  src/geo.c
Labels: release-notes, state:to-be-merged

#8445 GEOSEARCH bybox bug fixes and new fuzzy tester
  src/geo.c
  src/geohash_helper.c
  src/geohash_helper.h
  tests/unit/geo.tcl
Labels: release-notes

#8453 RM_ZsetRem: Delete key if empty
  runtest-moduleapi
  src/module.c
  tests/modules/Makefile
  tests/modules/zset.c
  tests/unit/moduleapi/zset.tcl
Labels: release-notes

#8416 Add --insecure option to command line tools.
  src/cli_common.c
  src/cli_common.h
  src/redis-benchmark.c
  src/redis-cli.c
Labels: approval-needed, release-notes, state:major-decision

#8444 Optimize HRANDFIELD and ZRANDMEMBER case 4 when ziplist encoded
  src/t_hash.c
  src/t_zset.c
  src/ziplist.c
  src/ziplist.h
Labels: approval-needed, release-notes

#8480 Fix Sentinel configuration rewrite.
  src/sentinel.c
Labels: release-notes

#8481 Fix duplicate replicas issue.
  src/sentinel.c
Labels: release-notes

#8486 redis-benchmark: Fix broken protocol when used with -a or --dbnum
  src/redis-benchmark.c
Labels: release-notes

#8446 Modules: In RM_HashSet, add COUNT_ALL flag and set errno
  runtest-moduleapi
  src/module.c
  src/redismodule.h
  tests/modules/Makefile
  tests/modules/hash.c
  tests/unit/moduleapi/hash.tcl
Labels: approval-needed, release-notes, state:major-decision

#8492 Escape unsafe field name characters in INFO.
  src/module.c
  src/server.c
  src/server.h
  src/util.c
  src/util.h
  tests/integration/redis-cli.tcl
  tests/modules/infotest.c
  tests/unit/info.tcl
  tests/unit/moduleapi/infotest.tcl
Labels: release-notes

#8414 Add child current processed keys to persistence info
  src/aof.c
  src/childinfo.c
  src/module.c
  src/rdb.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/integration/rdb.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr

#6281 optimize listpack for stream usage
  src/listpack.c
  src/listpack.h
  src/listpack_malloc.h
  src/t_stream.c
Labels: datastructure, release-notes

#8472 Remove redundant pubsub list to store the patterns.
  src/cluster.c
  src/dict.c
  src/pubsub.c
  src/server.c
  src/server.h
Labels: release-notes, state:to-be-merged

#8287 EXPIRE, EXPIREAT, SETEX, GETEX: Return error when expire time overflows
  src/expire.c
  src/t_string.c
  tests/unit/expire.tcl
Labels: approval-needed, release-notes, state:major-decision

#8456 Client tracking tracking-redir-broken push len is 2 not 3
  src/tracking.c
  tests/support/redis.tcl
  tests/unit/tracking.tcl
Labels: release-notes

#8517 Fix allowed length for REPLCONF ip-address.
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
Labels: release-notes

#8504 SRANDMEMBER RESP3 return should be Array, not Set
  src/t_hash.c
  src/t_set.c
  src/t_zset.c
Labels: release-notes, state:major-decision

#8390 In XADD take deleted items into consideration when switch to new node
  src/t_stream.c
Labels: release-notes

#8483 Remove acl subcommand validation if fully added command exists.
  src/acl.c
  tests/unit/acl.tcl
Labels: state:major-decision

#8520 Remove race condition and consistency issues with client pause threaded IO
  src/blocked.c
  src/networking.c
  src/server.h
Labels: release-notes

#8533 Fix compile errors with no HAVE_MALLOC_SIZE.
  .github/workflows/daily.yml
  src/zmalloc.c
Labels: release-notes

#8545 Use malloc_usable_size() on FreeBSD.
  src/zmalloc.h
Labels: release-notes

#8257 Fix quicklistDelRange dead code, delete range wrong
  src/quicklist.c
Labels: state:to-be-merged

#8516 Shared reusable client for RM_Call()
  src/module.c
  src/pubsub.c
  src/server.h
  tests/unit/moduleapi/misc.tcl
Labels: release-notes

#8508 Module API for getting user name of a client
  src/module.c
  src/redismodule.h
Labels: approval-needed, release-notes, state:major-decision
