Repository redis/redis, pull requests merged in 2021-10, with the labels that each got.

#9573 Unify dbSyncDelete and dbAsyncDelete
  src/db.c
  src/lazyfree.c
Labels: state:to-be-merged

#9528 Remove argument count limit, dynamically grow argv.
  src/networking.c
  src/server.h
  tests/unit/protocol.tcl
Labels: state:to-be-merged, release-notes

#9577 decrby LLONG_MIN caused nagation overflow.
  src/t_string.c
  tests/unit/type/incr.tcl
Labels: state:to-be-merged, release-notes

#9562 improve the stability and correctness of "Test child sending info"
  tests/integration/rdb.tcl
Labels: state:to-be-merged

#9602 Avoid argv memcpy when queuing a multi command.
  src/multi.c
  src/server.h
Labels: state:to-be-merged

#9535 Test can fail if flushdb triggers a bgsave
  tests/unit/other.tcl
Labels: state:to-be-merged

#9511 Implement anetPipe() to combine creating pipe and setting flags
  src/anet.c
  src/anet.h
  src/aof.c
  src/childinfo.c
  src/module.c
  src/rdb.c
  src/server.c
Labels: state:to-be-merged

#9287 Hide empty replicas from CLUSTER SLOTS responses
  src/cluster.c
  tests/cluster/tests/22-replica-in-sync.tcl
Labels: state:major-decision, release-notes, approval-needed

#9545 Use fcntl(fd,F_FULLFSYNC) instead of fsync on OSX, improve power failure safety
  src/config.h
Labels: state:to-be-merged, release-notes

#9641 fix typos in module doc / header
  src/module.c
  src/redismodule.h
Labels: state:to-be-merged

#4373 Code cleanup, resolve an issue identified by cppcheck
  src/bitops.c
Labels: state:to-be-merged

#9600 Add RedisModule_KeyExists
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, release-notes, approval-needed

#9389 Make Cluster-bus port configurable with new cluster-port config
  redis.conf
  src/cluster.c
  src/cluster.h
  src/config.c
  src/server.h
  tests/unit/introspection.tcl
Labels: state:major-decision

#9483 Release clients blocked on module commands in cluster resharding and down state
  runtest-moduleapi
  src/cluster.c
  tests/modules/blockonkeys.c
  tests/test_helper.tcl
  tests/unit/cluster.tcl
  tests/unit/moduleapi/cluster.tcl
Labels: release-notes

#9504 Treat subcommands as commands
  redis.conf
  runtest-moduleapi
  src/acl.c
  src/aof.c
  src/config.c
  src/db.c
  src/module.c
  src/networking.c
  src/pubsub.c
  src/redismodule.h
  src/replication.c
  src/scripting.c
  src/sentinel.c
  src/server.c
  src/server.h
  src/t_string.c
  tests/modules/Makefile
  tests/modules/subcommands.c
  tests/unit/acl.tcl
  tests/unit/info.tcl
  tests/unit/introspection-2.tcl
  tests/unit/latency-monitor.tcl
  tests/unit/moduleapi/keyspecs.tcl
  tests/unit/moduleapi/subcommands.tcl
  tests/unit/type/stream.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, breaking-change
