Repository redis/redis, pull requests merged in 2021-03, with the labels that each got.

#8555 Make dbid check for SWAPDB command consistent with SELECT, MOVE, and COPY
  src/db.c
Labels: release-notes, state:to-be-merged

#8458 Fix compliation on arm64 Mac with jemalloc
  src/debug.c
Labels: release-notes, state:to-be-merged

#8510 Make port, tls-port and bind configurations modifiable
  src/cluster.c
  src/config.c
  src/server.c
  src/server.h
  tests/test_helper.tcl
  tests/unit/introspection.tcl
  tests/unit/networking.tcl
  tests/unit/tls.tcl
Labels: approval-needed, release-notes, state:major-decision

#8568 fix stream deep sanitization with deleted records
  src/t_stream.c
  tests/integration/corrupt-dump-fuzzer.tcl
  tests/integration/rdb.tcl
Labels: release-notes, state:to-be-merged

#8580 Redis 6.2.1
  .github/workflows/daily.yml
  00-RELEASENOTES
  src/Makefile
  src/acl.c
  src/cluster.c
  src/config.c
  src/config.h
  src/connection.c
  src/db.c
  src/debug.c
  src/fmacros.h
  src/lolwut5.c
  src/module.c
  src/pubsub.c
  src/quicklist.c
  src/redis-cli.c
  src/redismodule.h
  src/scripting.c
  src/server.c
  src/server.h
  src/setproctitle.c
  src/t_stream.c
  src/version.h
  src/zmalloc.c
  src/zmalloc.h
  tests/instances.tcl
  tests/integration/corrupt-dump-fuzzer.tcl
  tests/integration/logging.tcl
  tests/integration/rdb.tcl
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/info.tcl
  tests/unit/introspection.tcl
  tests/unit/moduleapi/misc.tcl
  tests/unit/networking.tcl
  tests/unit/tls.tcl
Labels: state:major-decision

#8583 Fix potential replication-4 test race condition.
  tests/integration/replication-4.tcl
Labels: state:to-be-merged

#8588 Fix client_recent_max_input/output_buffer in 'INFO CLIENTS' when all clients drop.
  src/server.c
Labels: release-notes

#8596 Fix RedisModule_IsAOFClient Redis Module API
  src/redismodule.h
Labels: release-notes

#8566 Improve redis-cli non-binary safe string handling.
  src/redis-cli.c
  tests/integration/redis-cli.tcl
Labels: release-notes

#8603 Fix FreeBSD <12.x builds.
  src/zmalloc.h
Labels: release-notes

#8618 Fix edge-case when a module client is unblocked
  src/module.c
Labels: release-notes

#8311 __quicklistCompress may compress more node than required
  src/quicklist.c
Labels: release-notes, state:to-be-merged

#8620 Fix memory info on FreeBSD.
  src/zmalloc.c
Labels: release-notes

#8628 strip % sign from current_fork_perc info field
  src/server.c
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8559 Cleanup ZADD_* flags
  src/module.c
  src/server.h
  src/t_zset.c
Labels: state:to-be-merged

#8617 Fix some issues with modules and MULTI/EXEC
  src/module.c
  src/multi.c
  src/server.c
  src/server.h
  tests/modules/propagate.c
  tests/unit/moduleapi/propagate.tcl
Labels: release-notes

#8633 Process hello command even if the default user has no permissions.
  src/acl.c
  tests/unit/acl.tcl
Labels: release-notes

#8629 allow RESET during busy scripts
  src/server.c
Labels: release-notes

#8567 Sentinel: fix info_refresh time before sentinel get first response
  src/sentinel.c
Labels: release-notes

#8541 Optimize CLUSTER SLOTS reply by reducing unneeded loops
  src/cluster.c
  tests/cluster/tests/19-cluster-nodes-slots.tcl
Labels: release-notes, state:to-be-merged

#8654 Missing EXEC on modules propagation after failed EVAL execution
  src/module.c
  src/scripting.c
  src/server.c
  tests/unit/moduleapi/propagate.tcl
Labels: release-notes

#8584 Redact slowlog entries for config with sensitive data.
  src/acl.c
  src/blocked.c
  src/config.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/slowlog.tcl
Labels: release-notes, state:major-decision

#8655 Fix server won't start on alpine/libmusl without IPv6.
  src/server.c
Labels: release-notes, state:to-be-merged

#8631 set module eviction context flag only in masters
  src/module.c
Labels: release-notes

#8659 Fix issue where error replies are not counted on stats
  src/db.c
Labels: release-notes, state:to-be-merged

#8592 Fix typo in t_stream.c
  src/t_stream.c
Labels: class:text

#5697 Fix incorrect presentation in README.md
  README.md
Labels: class:text

#3543 Update README.md
  README.md
Labels: class:text

#8647 When tests exit normally, some processes may still be alive
  src/server.c
  tests/support/server.tcl
Labels: state:to-be-merged

#8661 Fix script kill to work also on scripts that use pcall
  src/scripting.c
  tests/unit/scripting.tcl
Labels: release-notes, state:to-be-merged

#8679 Fix race in replication test
  tests/integration/replication.tcl
Labels: state:to-be-merged

#8674 fix race in diskless load cluster tests
  tests/cluster/tests/17-diskless-load-swapdb.tcl
Labels: state:to-be-merged

#8645 Fix slowdown due to child reporting CoW.
  src/childinfo.c
  src/server.c
  src/server.h
  src/zmalloc.c
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8644 Add support for reading encrypted keyfiles.
  redis.conf
  src/config.c
  src/server.h
  src/tls.c
  tests/unit/tls.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr

#8651 resolve cluster failover timeout when master repl_offset is 0
  src/cluster.c
  src/cluster.h
Labels: release-notes, state:to-be-merged

#8685 Avoid evaluating log arguments when log filtered by level.
  src/server.c
  src/server.h
Labels: state:to-be-merged

#8564 Add GetAbsExpire/SetAbsExpire for module
  src/module.c
  src/redismodule.h
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8638 Fixes a typo in DEBUG HELP
  src/debug.c
Labels: state:to-be-merged

#8681 Corrupt stream key access to uninitialized memory
  src/t_stream.c
  tests/integration/corrupt-dump.tcl
Labels: state:to-be-merged

#8688 Remove cron saving during BGSAVE test.
  tests/unit/other.tcl
Labels: state:to-be-merged

#8666 Remove obsolete wait3() / wait4() and fix a valgrind warning in checkChildrenDone()
  src/aof.c
  src/module.c
  src/rdb.c
  src/sentinel.c
  src/server.c
  tests/integration/replication.tcl
Labels: state:to-be-merged

#8585 Skip unnecessary check for pong received
  src/cluster.c
Labels: approval-needed

#8632 Fix SLOWLOG for blocked commands
  src/blocked.c
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/slowlog.tcl
Labels: release-notes, state:to-be-merged

#8689 Introduce fast path to bypass expensive serveClientsBlockedOnKeyByModule call
  src/blocked.c
Labels: release-notes

#8534 make processCommand check publish channel permissions.
  src/acl.c
  src/multi.c
  src/pubsub.c
  src/scripting.c
  src/server.c
  src/server.h
  tests/unit/acl.tcl
Labels: release-notes

#8705 fix redis-cli.c handling of rediss:// tlsscheme
  src/redis-cli.c
Labels: release-notes

#8715 Restore old client 'processCommandAndResetClient' to fix false dead client indicator
  src/networking.c
  tests/unit/scripting.tcl
Labels: release-notes, state:to-be-merged

#8719 Fix config rewrite with an empty "save" parameter.
  src/config.c
  tests/unit/introspection.tcl
Labels: release-notes

#8722 fix config rewrite
  src/config.c
  tests/unit/introspection.tcl
Labels: state:to-be-merged

#8699 Minor client output buffer optimizations
  src/networking.c
Labels: state:to-be-merged

#8587 Add support for plaintext clients in TLS cluster
  redis.conf
  src/cluster.c
  src/cluster.h
  src/config.c
  src/server.h
  tests/cluster/tests/04-resharding.tcl
  tests/cluster/tests/15-cluster-slots.tcl
  tests/instances.tcl
  tests/support/cluster.tcl
  tests/support/redis.tcl
Labels: approval-needed, release-notes, state:major-decision

#8653 Add replica-announced config option
  redis.conf
  src/config.c
  src/sentinel.c
  src/server.c
  src/server.h
  tests/sentinel/tests/10-replica-priority.tcl
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8724 XAUTOCLAIM: JUSTID should prevent incrementing delivery_count
  src/t_stream.c
Labels: release-notes
