Repository redis/redis, pull requests merged in 2021-07, with the labels that each got.

#9176 Don't start in sentinel mode if only the folder name contains redis-sentinel
  src/server.c
Labels: release-notes, state:to-be-merged

#9173 Fix bug in sdscatfmt when % is the last format char
  src/sds.c
Labels: state:to-be-merged

#9192 fix valgrind issues with recently added test in modules/blockonbackground
  tests/modules/blockonbackground.c
Labels: state:to-be-merged

#9196 add missing skips to daily cycle
  .github/workflows/daily.yml
Labels: state:to-be-merged

#9177 Use accept4 on linux (refresh of #1339)
  src/anet.c
  src/cluster.c
  src/config.h
  src/networking.c
Labels: state:to-be-merged

#9178 hrandfield and zrandmember with count should return emptyarray when key does not exist.
  src/t_hash.c
  src/t_zset.c
  tests/unit/type/hash.tcl
  tests/unit/type/set.tcl
  tests/unit/type/zset.tcl
Labels: release-notes, state:to-be-merged

#9096 Reset db num and transaction state from redis-cli prompt after RESET …
  src/redis-cli.c
Labels: release-notes

#9200 a little optimization in touchAllWatchedKeysInDb
  src/multi.c
Labels: state:to-be-merged

#9136 Direct redis-cli repl prints to stderr, because --rdb can print to stdout. fflush stdout after responses
  src/redis-cli.c
  tests/integration/redis-cli.tcl
Labels: release-notes, state:to-be-merged

#9215 Start redis-check-aof/redis-check-rdb only if executable name contains
  src/server.c
Labels: release-notes

#9218 Add test for ziplist (nextdiff == -4 && reqlen < 4)
  src/ziplist.c
Labels: state:to-be-merged

#8767 Do not install a file event to send data to rewrite child when parent stop sending diff to child in aof rewrite.
  src/aof.c
Labels: state:to-be-merged

#9194 Fail Exec command in case a watched key is expired
  src/multi.c
  src/server.c
  src/server.h
  tests/unit/multi.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#9210 Add missing comma in memory/xgroup command help message.
  src/object.c
  src/t_stream.c
Labels: state:to-be-merged

#9233 Fix compatibility with OpenSSL 1.1.0.
  src/tls.c
Labels: release-notes

#9150 fix timeout spell error
  src/redis-cli.c
Labels: class:text

#9230 Set TCP keepalive on inbound clusterbus connections
  src/cluster.c
Labels: release-notes, state:to-be-merged

#9244 SMOVE only notify dstset when the addition is successful.
  src/t_set.c
  tests/unit/type/set.tcl
Labels: release-notes, state:to-be-merged

#2946 Update Lua debugging help message commands for consistency.
  src/scripting.c
Labels: class:text, state:to-be-merged

#2927 Fix format strings serverLogObjectDebugInfo to use unsigned
  src/debug.c
Labels: state:needs-coding, state:to-be-merged

#9249 Fix rank overflow in zslInsert with more than 2B entries.
  src/t_zset.c
Labels: release-notes

#9241 Fix missing separator in module info line (usedby and using lists)
  src/module.c
Labels: state:to-be-merged

#9208 Fix ACL category for SELECT, WAIT, ROLE, LASTSAVE, READONLY, READWRITE, ASKING
  redis.conf
  src/acl.c
  src/server.c
Labels: approval-needed, breaking-change, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#9191 On 32 bit platform, the bit position of GETBIT/SETBIT/BITFIELD/BITCOUNT,BITPOS may overflow
  .github/workflows/daily.yml
  src/bitops.c
  src/server.h
  tests/unit/bitops.tcl
Labels: release-notes, state:to-be-merged

#9031 Add INFO stat eviction_exceeded_time
  src/evict.c
  src/server.c
  src/server.h
Labels: release-notes, state:major-decision, state:needs-doc-pr

#9279 Fix LRU blue moon bug in RESTORE, RDB loading, module API
  src/object.c
Labels: release-notes, state:to-be-merged

#9280 Minor refactoring for rioConnRead and adding errno
  src/replication.c
  src/rio.c
Labels: state:to-be-merged

#9255 Free unused capacity in the cluster send buffer.
  src/cluster.c
Labels: cluster
