Repository redis/redis, pull requests merged in 2021-01, with the labels that each got.

#8260 Crash log would crash half way on commands with no arguments
  src/debug.c
Labels: state:to-be-merged

#8267 fix crash in redis-cli after making cluster backup
  src/redis-cli.c
Labels: release-notes, state:to-be-merged

#8281 Fix rare assertion as a result of: active defrag while loading
  src/replication.c
  src/server.c
Labels: state:to-be-merged

#8280 Fix uninitialized variable in new errorstats commit
  src/module.c
Labels: state:to-be-merged

#8227 GEOADD - add [CH] [NX|XX] options
  src/geo.c
  tests/unit/geo.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8283 sort Command lookupKeyRead and lookupKeyWrite are used on the opposite
  src/sort.c
Labels: release-notes

#8239 Swapdb should make transaction fail if there is any client watching keys
  src/db.c
  src/multi.c
  src/server.h
  tests/unit/multi.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#5531 HELP subcommand, continued
  src/acl.c
  src/cluster.c
  src/config.c
  src/debug.c
  src/latency.c
  src/module.c
  src/networking.c
  src/object.c
  src/pubsub.c
  src/scripting.c
  src/sentinel.c
  src/server.c
  src/slowlog.c
  src/t_stream.c
Labels: state:to-be-merged

#8285 remove unused call to zmalloc_size in defrag.c
  src/defrag.c
Labels: state:to-be-merged

#8266 Fix wrong order of key/value in Lua map response
  src/scripting.c
  tests/support/redis.tcl
  tests/unit/scripting.tcl
  tests/unit/tracking.tcl
Labels: approval-needed, release-notes, state:major-decision

#8270 Fix rdb checksum / crc64 on bigendian
  src/crcspeed.c
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#7973 Add XAUTOCLAIM
  src/networking.c
  src/server.c
  src/server.h
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#7844 New ZRANGESTORE Command
  src/server.c
  src/server.h
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8224 Add check for the MADV_FREE/fork arm64 Linux kernel bug
  redis.conf
  src/config.c
  src/server.c
  src/server.h
Labels: approval-needed, release-notes, state:major-decision

#8170 Add support for client pause WRITE
  src/blocked.c
  src/cluster.c
  src/db.c
  src/evict.c
  src/expire.c
  src/module.c
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  tests/unit/pause.tcl
  tests/unit/wait.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-code-doc, state:to-be-merged

#8176 Deduplicate bcast tracking clients (Or throw an error on conflict?)
  src/networking.c
  src/server.h
  src/tracking.c
  tests/unit/tracking.tcl
Labels: approval-needed, release-notes, state:needs-doc-pr, state:to-be-merged

#8294 Skip defrag tests on systems with bigger page sizes
  tests/unit/memefficiency.tcl
Labels: state:to-be-merged

#8169 XADD and XTRIM, Trim by MINID, and new LIMIT argument
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8259 GEOSEARCH - ANY option, for limited search that returns ASAP
  src/geo.c
  tests/unit/geo.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8296 Assert that clusterAddNode can't fail
  src/cluster.c
Labels: state:to-be-merged

#8306 Fix overflow of rdbWriteRaw return value
  src/rdb.c
Labels: state:to-be-merged

#8182 Optimize performance of clusterGenNodesDescription for large clusters
  src/cluster.c
  src/cluster.h
  tests/cluster/tests/18-cluster-nodes-slots.tcl
Labels: release-notes

#8258 Add lazyfree-lazy-user-flush config to control default behavior of FLUSH[ALL|DB], SCRIPT FLUSH
  redis.conf
  src/config.c
  src/db.c
  src/lazyfree.c
  src/scripting.c
  src/server.h
  tests/unit/scripting.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8356 Bugfix: Make modules blocked on keys unblock on commands like LPUSH
  src/blocked.c
  tests/modules/blockonkeys.c
  tests/unit/moduleapi/blockonkeys.tcl
Labels: release-notes, state:to-be-merged

#8357 Add tests to make sure that relative EXPIRE is propagated to replicas
  tests/unit/expire.tcl
Labels: state:to-be-merged

#8337 Fix description of the save conf directive
  redis.conf
Labels: approval-needed, release-notes, state:to-be-merged

#8242 Fix file-descriptor leaks in sentinel
  src/ae.c
  src/ae_epoll.c
  src/ae_evport.c
  src/ae_kqueue.c
  src/anet.c
  src/anet.h
  src/cluster.c
  src/module.c
  src/networking.c
  src/sentinel.c
  src/server.c
  tests/instances.tcl
  tests/sentinel/run.tcl
  tests/sentinel/tests/includes/init-tests.tcl
  tests/sentinel/tests/includes/notify.sh
Labels: state:to-be-merged

#8344 More modules API ref formatting fixes
  src/module.c
  src/modules/gendoc.rb
Labels: state:to-be-merged

#8367 Fix firstkey,lastkey,step of some commands
  src/server.c
Labels: release-notes

#8292 Free bsd
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  src/server.c
Labels: state:to-be-merged

#8371 CONFIG REWRITE should honor umask settings.
  src/config.c
  src/server.c
  src/server.h
Labels: release-notes

#8381 In dbOverwrite moduleNotifyKeyUnlink should use old val
  src/db.c
Labels: release-notes

#8271 Sentinel: Fix Config Dependency and Rewrite Sequence issue
  src/config.c
  src/sentinel.c
  src/server.c
  src/server.h
  tests/instances.tcl
  tests/sentinel/run.tcl
  tests/sentinel/tests/00-base.tcl
  tests/sentinel/tests/includes/sentinel.conf
  tests/sentinel/tests/includes/start-init-tests.tcl
Labels: release-notes, state:to-be-merged

#8391 Add tests for RESP3 responce of ZINTER and ZRANGE
  src/t_zset.c
  tests/support/redis.tcl
  tests/unit/type/zset.tcl
Labels: state:to-be-merged

#8303 Implement rdb-only replication
  src/redis-cli.c
  src/replication.c
  src/server.h
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#8327 GETEX, GETDEL and SET PXAT/EXAT
  src/aof.c
  src/server.c
  src/server.h
  src/t_string.c
  tests/integration/aof.tcl
  tests/unit/expire.tcl
  tests/unit/type/string.tcl
Labels: approval-needed, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8405 Avoid assertions when testing arm64 cow bug.
  src/server.c
Labels: release-notes, state:to-be-merged

#3623 Add 'set-proc-title' config so that this mechanism can be disabled
  redis.conf
  src/config.c
  src/server.c
  src/server.h
  tests/unit/introspection.tcl
Labels: approval-needed

#8282 Add hostname support in Sentinel.
  sentinel.conf
  src/anet.c
  src/anet.h
  src/sentinel.c
  tests/instances.tcl
  tests/sentinel/tests/08-hostname-conf.tcl
  tests/sentinel/tests/09-acl-support.tcl
  tests/sentinel/tests/includes/init-tests.tcl
Labels: approval-needed, release-notes, state:major-decision

#8288 Add modules API for streams
  runtest-moduleapi
  src/module.c
  src/redismodule.h
  src/stream.h
  src/t_stream.c
  tests/modules/Makefile
  tests/modules/stream.c
  tests/unit/moduleapi/stream.tcl
Labels: approval-needed, release-notes, state:major-decision

#8347 Redis exit for fsync error when the AOF fsync policy is 'always'
  src/aof.c
Labels: approval-needed, state:major-decision, state:to-be-merged

#8289 Modules: Add event for fork child birth and termination
  src/module.c
  src/redismodule.h
  src/server.c
Labels: approval-needed, release-notes, state:major-decision

#8397 Add proc-title-template option.
  redis.conf
  src/config.c
  src/sds.c
  src/sds.h
  src/server.c
  src/server.h
  tests/unit/other.tcl
Labels: approval-needed, release-notes, state:major-decision

#8315 implement FAILOVER command
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  tests/integration/failover.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8030 AOF: recover from last write error after turn on appendonly again
  src/aof.c
  src/server.c
Labels: release-notes, state:to-be-merged

#8297 Add hrandfield and zrandmember
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_set.c
  src/t_zset.c
  src/ziplist.c
  src/ziplist.h
  tests/support/util.tcl
  tests/unit/type/hash.tcl
  tests/unit/type/set.tcl
  tests/unit/type/zset.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr

#7491 Enabled background and reply time tracking on blocked on keys/blocked on background work clients
  runtest-moduleapi
  src/blocked.c
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/blockonbackground.c
  tests/unit/moduleapi/blockonbackground.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr

#8424 Fix test issues from introduction of HRANDFIELD
  src/ziplist.c
  tests/integration/corrupt-dump.tcl
  tests/support/util.tcl
Labels: state:to-be-merged

#8425 temporarily disable sentinel test FD leak print
  tests/instances.tcl
Labels: state:to-be-merged
