Repository redis/redis, pull requests merged in 2021-08, with the labels that each got.

#9271 GEO* STORE with empty src key delete the dest key and return 0, not empty array
  src/geo.c
  tests/unit/geo.tcl
Labels: approval-needed, breaking-change, release-notes, state:major-decision, state:to-be-merged

#9113 Optimize quicklist insert head/tail when node full but prev/next is NULL
  src/quicklist.c
Labels: state:to-be-merged

#2795 Add NX/XX/GT/LT options to EXPIRE command group
  src/expire.c
  src/server.c
  tests/unit/expire.tcl
Labels: release-notes, state:major-decision, state:needs-doc-pr, state:needs-test-code

#8930 When redis-cli received ASK, it didn't handle it
  src/redis-cli.c
  tests/helpers/fake_redis_node.tcl
  tests/integration/redis-cli.tcl
Labels: breaking-change, class:bug, release-notes, state:to-be-merged

#8521 Module api support for RESP3
  src/module.c
  src/redismodule.h
  tests/modules/reply.c
  tests/support/redis.tcl
  tests/unit/moduleapi/reply.tcl
  tests/unit/protocol.tcl
Labels: approval-needed, release-notes, state:major-decision

#8946 Add SINTERCARD/ZINTERCARD Commands
  src/server.c
  src/server.h
  src/t_set.c
  src/t_zset.c
  tests/unit/type/set.tcl
  tests/unit/type/zset.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr

#9130 Enabled -x option (Read last argument from STDIN) on redis-benchmark
  src/cli_common.c
  src/cli_common.h
  src/redis-benchmark.c
  src/redis-cli.c
Labels: approval-needed, release-notes, state:major-decision

#9202 Unified Lua and modules reply parsing and added resp3 support to RM_Call
  src/Makefile
  src/call_reply.c
  src/call_reply.h
  src/debug.c
  src/module.c
  src/redismodule.h
  src/resp_parser.c
  src/resp_parser.h
  src/scripting.c
  src/server.h
  tests/modules/basics.c
  tests/support/redis.tcl
  tests/unit/moduleapi/basics.tcl
  tests/unit/scripting.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#8974 Use madvise(MADV_DONTNEED) to release memory to reduce COW
  src/aof.c
  src/childinfo.c
  src/object.c
  src/rdb.c
  src/server.c
  src/server.h
  src/zmalloc.c
  src/zmalloc.h
  tests/integration/dismiss-mem.tcl
  tests/test_helper.tcl
Labels: approval-needed, release-notes, state:major-decision, state:needs-doc-pr, state:to-be-merged

#9228 dict struct memory optimizations
  src/cluster.c
  src/config.c
  src/db.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/expire.c
  src/latency.c
  src/lazyfree.c
  src/module.c
  src/networking.c
  src/object.c
  src/rdb.c
  src/redis-benchmark.c
  src/redis-cli.c
  src/replication.c
  src/scripting.c
  src/sentinel.c
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_set.c
  src/t_zset.c
Labels: approval-needed, release-notes, state:major-decision, state:to-be-merged

#9317 Add latency monitor sample when key is deleted via lazy expire
  src/db.c
  src/expire.c
  src/server.h
Labels: release-notes

#9316 Make sure execute SLAVEOF command in the right order in psync2 test.
  tests/integration/psync2.tcl
Labels: state:to-be-merged

#9304 Add debug config flag to print certain config values on engine crash
  src/config.c
  src/debug.c
  src/server.h
Labels: state:to-be-merged

#9297 Sanitize dump payload: fix empty keys when RDB loading and restore command
  src/cluster.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  tests/assets/corrupt_empty_keys.rdb
  tests/integration/corrupt-dump.tcl
Labels: state:to-be-merged, release-notes

#9321 Improvements to corrupt payload sanitization
  src/dict.c
  src/listpack.c
  src/listpack.h
  src/object.c
  src/rdb.c
  src/server.h
  src/t_stream.c
  src/ziplist.c
  tests/integration/corrupt-dump.tcl
Labels: release-notes

#9302 corrupt-dump-fuzzer test, avoid creating junk keys
  tests/integration/corrupt-dump-fuzzer.tcl
  tests/support/util.tcl
Labels: state:to-be-merged

#9322 Ignore resize threshold on idle qbuf resizing
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/querybuf.tcl
Labels: state:to-be-merged

#8910 sds.c: Fix potential overflow in sdsll2str.
  src/sds.c
Labels: state:to-be-merged

#9340 Allow master to replicate command longer than replica's query buffer limit
  src/networking.c
  tests/integration/replication-3.tcl
Labels: state:to-be-merged

#9299 Add SORT_RO command
  src/server.c
  src/server.h
  src/sort.c
  tests/unit/sort.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#9338 Cleanup: createAOFClient uses createClient to avoid overlooked mismatches
  src/aof.c
  src/networking.c
Labels: state:to-be-merged

#8887 Replace all usage of ziplist with listpack for t_hash
  redis.conf
  src/aof.c
  src/config.c
  src/db.c
  src/defrag.c
  src/listpack.c
  src/listpack.h
  src/module.c
  src/object.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_stream.c
  tests/assets/hash-ziplist.rdb
  tests/integration/convert-ziplist-hash-on-load.tcl
  tests/integration/convert-zipmap-hash-on-load.tcl
  tests/integration/corrupt-dump.tcl
  tests/test_helper.tcl
  tests/unit/aofrw.tcl
  tests/unit/keyspace.tcl
  tests/unit/scan.tcl
  tests/unit/type/hash.tcl
Labels: state:major-decision, release-notes

#9346 Format fixes and naming. SentReplyOnKeyMiss -> addReplyOrErrorObject
  src/db.c
  src/networking.c
  src/object.c
  src/server.h
Labels: state:to-be-merged

#9350 fix a compilation error around madvise when make with jemalloc on MacOS
  src/object.c
  src/server.c
  src/zmalloc.c
Labels: state:to-be-merged

#9352 support regex in "--only" in runtest
  tests/support/test.tcl
  tests/test_helper.tcl
Labels: state:to-be-merged

#9347 Redis-cli monitor and pubsub can be aborted with Ctrl+C, keeping the cli alive
  src/redis-cli.c
Labels: state:to-be-merged, release-notes

#9403 BITSET and BITFIELD SET only propagate command when the value changed.
  src/bitops.c
  tests/unit/bitops.tcl
Labels: state:to-be-merged, release-notes

#9313 config memory limits: handle values larger than (signed) LLONG_MAX
  src/config.c
  src/util.c
  src/util.h
Labels: state:to-be-merged

#5722 Fix boundary problem of adjusting open files limit.
  src/server.c
Labels: state:to-be-merged

#9146 redis-benchmark: make show throughput in only one thread.
  src/redis-benchmark.c
Labels: state:to-be-merged

#9308 Better error handling for updateClientOutputBufferLimit.
  src/config.c
  tests/unit/obuf-limits.tcl
Labels: state:to-be-merged

#9409 Use sync_file_range to optimize fsync if possible
  redis.conf
  src/config.h
  src/rio.c
  src/server.h
Labels: state:to-be-merged, release-notes

#9426 Tune timeout of active defrag test
  tests/unit/memefficiency.tcl
Labels: state:to-be-merged

#9356 Slot-to-keys using dict entry metadata
  src/cluster.c
  src/cluster.h
  src/db.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/lazyfree.c
  src/server.c
  src/server.h
Labels: state:to-be-merged, state:major-decision, release-notes
