Repository redis/redis, pull requests merged in 2022-05, with the labels that each got.

#10662 fix typo in 'setTypeRandomElement' doc comment
  src/t_set.c
Labels: class:text

#10667 support `tcp-keepalive` config interval on macOs
  src/anet.c
Labels: release-notes

#3672 cleanup: use ZIPLIST_ENTRY_END macro instead of 1
  src/ziplist.c
Labels: state:to-be-merged

#10688 update redismodule notify defines to be in sync with server
  src/redismodule.h
Labels: state:to-be-merged, release-notes

#10690 Fix --save command line regression in redis 7.0
  src/config.c
  tests/assets/default.conf
  tests/support/server.tcl
  tests/unit/introspection.tcl
Labels: release-notes, 7.0-must-have

#10670 fix some typos in "t_zset.c"
  src/t_zset.c
Labels: class:text

#10683 CLUSTER SHARDS should returns slots as integers, not strings
  src/cluster.c
Labels: state:major-decision, release-notes, breaking-change

#10660 redis-server command line arguments support take one bulk string with spaces for MULTI_ARG configs parsing. And allow options value to use the -- prefix
  src/config.c
  src/server.c
  tests/unit/introspection.tcl
Labels: release-notes, breaking-change, 7.0-must-have

#10645 Update comments on command args, and a misleading error reply
  src/sentinel.c
  src/server.c
  src/t_list.c
  src/t_set.c
  tests/unit/type/list.tcl
Labels: class:text

#10723 re-add SENTINEL SLAVES command, missing in redis 7.0
  src/commands.c
  src/commands/sentinel-slaves.json
Labels: state:to-be-merged, 7.0-must-have

#10726 Replica fail and retry the PSYNC if the master is unresponsive
  src/replication.c
Labels: release-notes

#10740 Fix typos in module comment / documentation
  src/module.c
  src/redismodule.h
Labels: class:text

#10753 Fix memory leak in streamGetEdgeID
  src/t_stream.c
Labels: state:to-be-merged

#10699 Scripts that declare the `no-writes` flag are implicitly `allow-oom` too.
  src/script.c
  src/server.c
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes

#10636 Add warning for suspected slow system clocksource setting
  src/Makefile
  src/latency.c
  src/latency.h
  src/server.c
  src/syscheck.c
  src/syscheck.h
  src/zmalloc.c
  src/zmalloc.h
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-must-have

#10764 Fix BZMPOP gets unblocked by non-key args and returns them
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: 7.0-must-have

#10763 improve logging around AOF file creation and loading
  src/aof.c
  src/server.c
Labels: 7.0-must-have

#10781 Fix outdated comment about flags in moduleCreateArgvFromUserFormat
  src/functions.c
  src/module.c
  tests/README.md
  tests/unit/tracking.tcl
Labels: class:text

#10767 Fix ZRANGESTORE crash when zset_max_listpack_entries is 0
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: state:to-be-merged, 7.0-must-have

#10784 Fix sentinel disconnect test timing issue after auth-pass change
  tests/sentinel/tests/03-runtime-reconf.tcl
Labels: state:to-be-merged

#10785 fix typo in quicklist.c
  src/quicklist.c
Labels: class:text

#10791 fixes function cache_memory accounting stats bug
  src/functions.c
Labels: state:to-be-merged

#10728 Add readonly flag to EVAL_RO, EVALSHA_RO and FCALL_RO
  src/commands.c
  src/commands/eval_ro.json
  src/commands/evalsha_ro.json
  src/commands/fcall_ro.json
  src/server.c
  tests/unit/acl.tcl
  tests/unit/tracking.tcl
Labels: release-notes, 7.0-must-have

#10783 Fix streamParseAddOrTrimArgsOrReply function minor comment issue
  src/t_stream.c
Labels: class:text

#10792 Sharded pubsub publish messagebulk as smessage
  src/pubsub.c
  src/server.c
  src/server.h
  src/tracking.c
  tests/cluster/tests/25-pubsubshard-slot-migration.tcl
  tests/unit/moduleapi/publish.tcl
  tests/unit/pubsubshard.tcl
Labels: breaking-change, 7.0-must-have

#10062 Adds isolated netstats for replication.
  src/networking.c
  src/rdb.c
  src/replication.c
  src/rio.c
  src/rio.h
  src/server.c
  src/server.h
Labels: state:major-decision, release-notes, approval-needed

#10795 Add module API RM_MallocUsableSize
  src/module.c
  src/redismodule.h
Labels: state:major-decision, release-notes, approval-needed
