Repository redis/redis, pull requests merged in 2022-11, with the labels that each got.

#11343 Re-design cluster link send buffer to improve memory management
  src/cluster.c
  src/cluster.h
  src/config.c
  src/server.h
  tests/cluster/cluster.tcl
  tests/cluster/tests/24-links.tcl
  tests/support/cluster_util.tcl
  tests/test_helper.tcl
  tests/unit/cluster/links.tcl
Labels: release-notes

#11434 Block some specific characters in module command names
  src/module.c
  tests/modules/subcommands.c
Labels: state:major-decision, approval-needed

#11224 Retain ACL categories used to generate ACL for displaying them later
  src/acl.c
  tests/unit/acl.tcl
Labels: state:major-decision, release-notes

#11407 Use jemalloc by default also on ARM
  src/Makefile
Labels: release-notes, breaking-change

#11439 Deprecate QUIT
  src/commands.c
  src/commands/quit.json
Labels: state:needs-doc-pr, state:major-decision, release-notes

#11290 Listpack encoding for sets
  redis.conf
  src/aof.c
  src/config.c
  src/db.c
  src/defrag.c
  src/intset.c
  src/intset.h
  src/listpack.c
  src/listpack.h
  src/object.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/server.h
  src/t_set.c
  src/t_zset.c
  tests/unit/keyspace.tcl
  tests/unit/scan.tcl
  tests/unit/type/set.tcl
Labels: state:major-decision, release-notes, approval-needed

#11482 Add test to cover NAN reply using a module
  tests/modules/reply.c
  tests/unit/moduleapi/reply.tcl
Labels: state:major-decision

#11500 Module CLIENT_CHANGE, Fix crash on free blocked client with DB!=0
  src/module.c
  tests/unit/moduleapi/hooks.tcl
Labels: release-notes

#11510 Explicitly send function commands to monitor
  src/functions.c
  tests/unit/introspection.tcl
Labels: release-notes

#11303 Add listpack encoding for list
  src/aof.c
  src/defrag.c
  src/lazyfree.c
  src/listpack.c
  src/listpack.h
  src/module.c
  src/object.c
  src/quicklist.c
  src/quicklist.h
  src/rdb.c
  src/server.h
  src/sort.c
  src/t_list.c
  tests/integration/rdb.tcl
  tests/unit/aofrw.tcl
  tests/unit/keyspace.tcl
  tests/unit/moduleapi/list.tcl
  tests/unit/sort.tcl
  tests/unit/type/list-common.tcl
  tests/unit/type/list.tcl
Labels: state:major-decision, release-notes, approval-needed

#10536 Introduce Shard IDs to logically group nodes in cluster mode
  src/cluster.c
  src/cluster.h
  src/commands.c
  src/commands/cluster-myshardid.json
  src/server.h
  tests/cluster/cluster.tcl
  tests/cluster/tests/28-cluster-shards.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#11214 Add CONFIG SET and GET loglevel feature in Sentinel
  sentinel.conf
  src/sentinel.c
  tests/sentinel/tests/01-conf-update.tcl
Labels: release-notes, approval-needed

#11199 Module API to allow writes after key space notification hooks
  runtest-moduleapi
  src/blocked.c
  src/cluster.c
  src/evict.c
  src/expire.c
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/keyspace_events.c
  tests/modules/postnotifications.c
  tests/unit/moduleapi/keyspace_events.tcl
  tests/unit/moduleapi/postnotifications.tcl
Labels: state:major-decision, release-notes, approval-needed

#10745 [BUG] Fix announced ports not updating on local node when updated at runtime
  src/cluster.c
  src/cluster.h
  src/config.c
  tests/unit/cluster/announced-endpoints.tcl
Labels: release-notes

#11522 Simplified geoAppendIfWithinShape() and removed spurious calls do sdsdup and sdsfree
  src/geo.c
Labels: release-notes, action:run-benchmark

#11235 Add withscore option to ZRANK and ZREVRANK.
  src/commands.c
  src/commands/zrank.json
  src/commands/zrevrank.json
  src/server.h
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: state:needs-doc-pr, state:to-be-merged, release-notes, approval-needed

#11096 benchmark ignore CONFIG GET error
  src/redis-benchmark.c
Labels: release-notes

#11521 Reduce eval related overhead introduced in v7.0 by evalCalcFunctionName
  src/eval.c
  src/functions.c
  src/networking.c
  src/server.h
Labels: action:run-benchmark

#9406 Add a special notification unlink available only for modules
  src/db.c
  src/dict.c
  src/dict.h
  src/evict.c
  src/expire.c
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  src/t_set.c
  src/t_string.c
  tests/modules/hooks.c
  tests/unit/moduleapi/hooks.tcl
Labels: state:major-decision, release-notes, approval-needed

#11099 Stream consumers: Re-purpose seen-time, add active-time
  src/blocked.c
  src/rdb.c
  src/rdb.h
  src/stream.h
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: release-notes, breaking-change

#11556 changing addReplySds and sdscat to addReplyStatusLength() within luaReplyToRedisReply()
  src/script_lua.c
  src/server.h
Labels: action:run-benchmark

#11557 Improve TLS error handling.
  src/replication.c
  src/tls.c
Labels: release-notes
