Repository redis/redis, pull requests merged in 2022-04, with the labels that each got.

#10489 Turn into replica on SETSLOT
  src/cluster.c
  tests/cluster/tests/12-replica-migration-2.tcl
  tests/unit/cluster.tcl
Labels: 7.0-must-have

#10526 Remove outdated utils/hashtable/rehashing.c
  utils/hashtable/README
  utils/hashtable/rehashing.c
Labels: state:to-be-merged

#10500 Functions: Move library meta data to be part of the library payload.
  src/aof.c
  src/commands.c
  src/commands/function-load.json
  src/functions.c
  src/functions.h
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  tests/cluster/tests/00-base.tcl
  tests/integration/redis-cli.tcl
  tests/integration/replication-4.tcl
  tests/integration/replication.tcl
  tests/support/redis.tcl
  tests/unit/aofrw.tcl
  tests/unit/cluster.tcl
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, breaking-change, 7.0-must-have

#10398 Update json command files so they only include syntax related information
  src/commands.c
  src/commands/client-pause.json
  src/commands/cluster-slots.json
  src/commands/flushall.json
  src/commands/flushdb.json
  src/commands/monitor.json
  src/commands/rename.json
  src/commands/script-flush.json
  src/commands/shutdown.json
  src/commands/subscribe.json
Labels: 7.0-must-have

#10550 Fix auto-aof-rewrite-percentage based AOFRW trigger after restart
  src/aof.c
Labels: release-notes, 7.0-must-have

#10560 Fix an mistake in comment
  src/resp_parser.h
Labels: class:text

#10544 COMMAND DOCS shows module name, where applicable
  src/module.c
  src/server.c
  src/server.h
  tests/unit/moduleapi/cmdintrospection.tcl
  tests/unit/moduleapi/subcommands.tcl
Labels: state:major-decision, release-notes, approval-needed

#10541 Add RM_TryAlloc
  src/module.c
  src/redismodule.h
Labels: state:major-decision, release-notes, approval-needed

#3719 Make RM_OpenKey return a typed handle
  src/module.c
  src/redismodule.h
Labels: state:to-be-merged

#9678 Durability enhancement for appendfsync=always policy
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
Labels: release-notes

#10249 Add check min-slave-* feature when evaluating Lua scripts for 6.2
  src/scripting.c
  tests/integration/replication-4.tcl
Labels: release-notes

#10559 Allow specifying ACL reason for module log entry
  src/module.c
  src/redismodule.h
  tests/modules/aclcheck.c
  tests/unit/moduleapi/aclcheck.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change, 7.0-must-have

#10545 Add the deprecated_since field in command args of COMMAND DOCS
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  utils/generate-command-code.py
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10512 Keyspace event for new keys
  redis.conf
  src/config.c
  src/db.c
  src/notify.c
  src/server.h
  tests/unit/pubsub.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#10574 Optimize stream id sds creation on XADD key * (~20% saved cpu cycles)
  src/t_stream.c
Labels: release-notes, action:run-benchmark

#10575 Fix incorrect error code for eval scripts and fix test error checking
  src/eval.c
  src/function_lua.c
  tests/unit/acl-v2.tcl
  tests/unit/auth.tcl
  tests/unit/bitops.tcl
  tests/unit/geo.tcl
  tests/unit/introspection.tcl
  tests/unit/moduleapi/basics.tcl
  tests/unit/scripting.tcl
  tests/unit/type/hash.tcl
  tests/unit/type/incr.tcl
  tests/unit/type/list.tcl
  tests/unit/type/stream.tcl
Labels: 7.0-must-have

#10542 Add RM_MallocSizeString, RM_MallocSizeDict
  runtest-moduleapi
  src/module.c
  src/object.c
  src/redismodule.h
  tests/modules/Makefile
  tests/modules/mallocsize.c
  tests/unit/moduleapi/mallocsize.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10543 Add RM_PublishMessageShard
  runtest-moduleapi
  src/cluster.c
  src/cluster.h
  src/module.c
  src/notify.c
  src/pubsub.c
  src/redismodule.h
  src/sentinel.c
  src/server.h
  tests/modules/Makefile
  tests/modules/publish.c
  tests/support/util.tcl
  tests/unit/moduleapi/publish.tcl
  tests/unit/pubsubshard.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10486 Optimize integer zset scores in listpack (converting to string and back)
  src/listpack.c
  src/listpack.h
  src/rdb.c
  src/t_zset.c
  src/util.c
  src/util.h
Labels: action:run-benchmark

#10573 Fix RM_Yield bug processing future commands of the current client.
  src/module.c
  tests/unit/moduleapi/blockedclient.tcl
Labels: 7.0-must-have

#10601 Return 0 when config set out-of-range oom-score-adj-values
  src/config.c
  tests/unit/oom-score-adj.tcl
Labels: state:to-be-merged

#10582 Fixes around AOF failed rewrite rate limiting
  src/aof.c
  src/server.c
Labels: 7.0-must-have

#10349 Add socket-mark-id support for marking sockets.
  redis.conf
  src/anet.c
  src/anet.h
  src/config.c
  src/config.h
  src/server.c
  src/server.h
  tests/unit/introspection.tcl
Labels: state:major-decision, release-notes, approval-needed

#10603 Fixes around clients that must be obeyed. Replica report disk errors in PING.
  src/bitops.c
  src/module.c
  src/script.c
  src/server.c
  src/server.h
  src/t_stream.c
  src/t_string.c
  src/timeout.c
Labels: 7.0-must-have

#10502 Optimization: Use either monotonic or wall-clock to measure command execution time, to regain up to 4% execution time
  src/monotonic.c
  src/monotonic.h
  src/server.c
Labels: state:major-decision, action:run-benchmark

#10622 fix typo in "lcsCommand"
  src/t_string.c
Labels: class:text

#10623 Fix typo in function name "harndfieldReplyWithListpack"
  src/t_hash.c
Labels: class:text

#10614 Fix timing issue in slowlog redact test
  tests/unit/slowlog.tcl
Labels: state:to-be-merged

#10612 Fix regression not aborting transaction on error, and re-edit some error responses
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
  tests/modules/basics.c
  tests/modules/subcommands.c
  tests/unit/acl.tcl
  tests/unit/functions.tcl
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/moduleapi/subcommands.tcl
  tests/unit/other.tcl
Labels: release-notes, 7.0-must-have

#10634 Fix typos and limit unknown command error message
  src/bitops.c
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
Labels: state:to-be-merged, class:text

#10615 By default prevent cross slot operations in functions and scripts with #
  src/networking.c
  src/script.c
  src/script.h
  src/server.c
  src/server.h
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/cluster-scripting.tcl
  tests/unit/functions.tcl
  tests/unit/moduleapi/cluster.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-must-have

#10504 Set replicas to panic on disk errors, and optionally panic on replication errors
  redis.conf
  src/config.c
  src/debug.c
  src/networking.c
  src/server.c
  src/server.h
  tests/assets/default.conf
  tests/integration/replication-4.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change, 7.0-must-have

#10594 Allow configuring signaled shutdown flags
  redis.conf
  src/config.c
  src/server.c
  src/server.h
  tests/modules/moduleconfigs.c
  tests/unit/introspection.tcl
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#10643 Add module API flag for using enum configs as bit flags
  src/config.c
  src/module.c
  src/redismodule.h
  tests/modules/moduleconfigs.c
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: state:major-decision, 7.0-must-have

#10649 Delete renamed new incr aof when write manifest failed
  src/aof.c
Labels: 7.0-must-have

#10651 Lua readonly tables (CVE-2022-24736, CVE-2022-24735)
  deps/lua/src/lapi.c
  deps/lua/src/ldebug.c
  deps/lua/src/lobject.h
  deps/lua/src/ltable.c
  deps/lua/src/lua.h
  deps/lua/src/lvm.c
  src/eval.c
  src/function_lua.c
  src/script_lua.c
  src/script_lua.h
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes

#10659 Update the comments of commands introduced or updated in redis 7.0
  src/expire.c
  src/functions.c
  src/pubsub.c
  src/server.c
Labels: class:text
