Repository redis/redis, pull requests merged in 2022-01, with the labels that each got.

#9968 Generate RDB with Functions only via redis-cli --functions-rdb
  src/aof.c
  src/db.c
  src/debug.c
  src/functions.c
  src/networking.c
  src/rdb.c
  src/rdb.h
  src/redis-cli.c
  src/replication.c
  src/server.c
  src/server.h
  tests/integration/redis-cli.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#9872 Wait for replicas when shutting down
  .github/.codespellrc
  redis.conf
  src/blocked.c
  src/cluster.c
  src/commands.c
  src/commands/shutdown.json
  src/config.c
  src/db.c
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  tests/integration/psync2-master-restart.tcl
  tests/integration/shutdown.tcl
  tests/support/server.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/shutdown.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#10017 Report slot to keys map size in MEMORY STATS in cluster mode
  src/object.c
  src/server.c
  src/server.h
Labels: state:major-decision, release-notes, approval-needed

#10020 Make sure replicas don't write their own replies to the replication link
  src/networking.c
Labels: 7.0-must-have

#10041 Add DUMP RESTORE tests for redis-cli -x and -X options
  tests/integration/redis-cli.tcl
Labels: state:to-be-merged

#8621 Sharded pubsub implementation
  redis.conf
  src/acl.c
  src/cluster.c
  src/cluster.h
  src/commands.c
  src/commands/pubsub-shardchannels.json
  src/commands/pubsub-shardnumsub.json
  src/commands/spublish.json
  src/commands/ssubscribe.json
  src/commands/sunsubscribe.json
  src/config.c
  src/module.c
  src/networking.c
  src/pubsub.c
  src/redis-cli.c
  src/server.c
  src/server.h
  src/tracking.c
  tests/cluster/cluster.tcl
  tests/cluster/tests/19-cluster-nodes-slots.tcl
  tests/cluster/tests/23-multiple-slot-operations.tcl
  tests/cluster/tests/25-pubsubshard-slot-migration.tcl
  tests/cluster/tests/26-pubsubshard.tcl
  tests/instances.tcl
  tests/support/cluster.tcl
  tests/test_helper.tcl
  tests/unit/acl.tcl
  tests/unit/pubsubshard.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-must-have

#9530 Clusterbus extensions and hostname support
  redis.conf
  src/cluster.c
  src/cluster.h
  src/config.c
  src/debug.c
  src/server.c
  src/server.h
  tests/cluster/cluster.tcl
  tests/cluster/tests/27-endpoints.tcl
  tests/cluster/tests/includes/init-tests.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-must-have

#10048 Fix OOM error not raised of functions
  src/server.c
  tests/unit/scripting.tcl
Labels: class:bug, 7.0-must-have

#9788 Implement Multi Part AOF mechanism to avoid AOFRW overheads.
  .gitignore
  redis.conf
  src/aof.c
  src/config.c
  src/debug.c
  src/evict.c
  src/latency.c
  src/object.c
  src/rdb.c
  src/redis-check-rdb.c
  src/server.c
  src/server.h
  src/util.c
  src/util.h
  tests/assets/rdb-preamble.aof
  tests/instances.tcl
  tests/integration/aof-multi-part.tcl
  tests/integration/aof-race.tcl
  tests/integration/aof.tcl
  tests/support/aofmanifest.tcl
  tests/support/server.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/expire.tcl
  tests/unit/introspection.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10019 use startEvictionTimeProc() in config set maxmemory
  src/config.c
  src/evict.c
  src/server.h
  tests/unit/moduleapi/propagate.tcl
Labels: release-notes, approval-needed, 7.0-must-have

#10015 Ban snapshot-creating commands and other admin commands from transactions
  src/aof.c
  src/commands.c
  src/commands/psync.json
  src/commands/save.json
  src/commands/shutdown.json
  src/commands/sync.json
  src/rdb.c
  src/server.c
  src/server.h
  tests/unit/aofrw.tcl
  tests/unit/multi.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change, 7.0-must-have

#10044 `redis-cli --replica` reads dummy empty rdb instead of full snapshot
  src/rdb.c
  src/redis-cli.c
  src/replication.c
  src/server.c
  src/server.h
Labels: state:major-decision, release-notes

#10035 Add tests for blocking XREAD[GROUP] when the stream ran dry
  tests/unit/type/stream-cgroups.tcl
  tests/unit/type/stream.tcl
Labels: state:to-be-merged

#10057 Fix typos in aof.c / redis.conf
  redis.conf
  src/aof.c
Labels: state:to-be-merged

#9462 Added INFO LATENCYSTATS section: latency by percentile distribution/latency by cumulative distribution of latencies
  .gitignore
  deps/hdr_histogram/Makefile
  deps/hdr_histogram/hdr_alloc.c
  deps/hdr_histogram/hdr_alloc.h
  deps/hdr_histogram/hdr_histogram.c
  deps/hdr_histogram/hdr_histogram.h
  redis.conf
  src/Makefile
  src/blocked.c
  src/commands.c
  src/commands/latency-histogram.json
  src/config.c
  src/latency.c
  src/module.c
  src/server.c
  src/server.h
  src/zmalloc.c
  src/zmalloc.h
  tests/support/util.tcl
  tests/unit/info.tcl
  tests/unit/latency-monitor.tcl
  tests/unit/maxmemory.tcl
  tests/unit/moduleapi/blockonbackground.tcl
  tests/unit/obuf-limits.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, action:run-benchmark

#10004 Redis Function Libraries
  src/commands.c
  src/commands/function-info.json
  src/commands/function-list.json
  src/commands/function-load.json
  src/commands/function-restore.json
  src/db.c
  src/function_lua.c
  src/functions.c
  src/functions.h
  src/lazyfree.c
  src/rdb.c
  src/rdb.h
  src/replication.c
  src/script_lua.c
  src/script_lua.h
  src/server.c
  src/server.h
  tests/integration/redis-cli.tcl
  tests/integration/replication.tcl
  tests/unit/cluster.tcl
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10068 lpGetInteger returns int64_t, avoid overflow
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: release-notes, 7.0-must-have

#7425 add ok-stale and ok-loading flag for readonly/readwrite command
  src/commands.c
  src/commands/readonly.json
  src/commands/readwrite.json
Labels: release-notes

#10081 Make sure replicas don't write their own replies to the replication link
  src/networking.c
  src/server.h
Labels: 7.0-must-have

#10049 Support whitespace characters in appendfilename, and ban them in appenddirname
  src/aof.c
  src/config.c
  src/util.c
  src/util.h
  tests/integration/aof-multi-part.tcl
Labels: 7.0-must-have

#10080 fix redis crached by using eval with access to volatile keys
  src/script.c
Labels: 7.0-must-have

#10095 LPOP/RPOP with count against non existing list return null array
  src/t_list.c
  tests/unit/type/list.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change, 7.0-must-have

#9940 Reuse temporary client objects for blocked clients by module
  src/module.c
  src/networking.c
  src/server.c
  src/server.h
Labels: 7.0-must-have

#10096 Add script tests to cover keys with expiration time set
  src/db.c
  src/eval.c
  src/script.c
  src/server.h
  tests/unit/scripting.tcl
Labels: state:to-be-merged

#10102 Always create base AOF file when redis start from empty.
  src/aof.c
  src/module.c
  src/rdb.c
  src/redismodule.h
  tests/integration/aof-multi-part.tcl
  tests/modules/hooks.c
  tests/unit/moduleapi/hooks.tcl
Labels: state:major-decision, release-notes, breaking-change, 7.0-must-have

#10101 Added RM_MonotonicMicroseconds() API to provide monotonic time function
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, release-notes, approval-needed

#10107 Fix kill aof rewrite child test
  tests/unit/aofrw.tcl
Labels: state:to-be-merged

#10066 Function Flags support (no-writes, no-cluster, allow-state, allow-oom)
  src/commands.c
  src/commands/fcall.json
  src/commands/fcall_ro.json
  src/function_lua.c
  src/functions.c
  src/functions.h
  src/script.c
  src/script.h
  src/script_lua.c
  src/script_lua.h
  src/server.c
  tests/cluster/tests/00-base.tcl
  tests/integration/redis-cli.tcl
  tests/unit/cluster.tcl
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10115 Fix function no-cluster flag test
  tests/cluster/tests/00-base.tcl
Labels: state:to-be-merged

#10117 Fix typo in doc for PUBSUB command
  src/commands.c
  src/commands/pubsub.json
Labels: class:text

#10116 fix zmalloc_get_rss on NetBSD
  src/zmalloc.c
Labels: release-notes

#10121 Fix timing issue in PSETEX/PEXPIRE sub-second expire tests
  tests/unit/expire.tcl
Labels: state:to-be-merged

#10103 show subcommands latencystats
  src/latency.c
  src/server.c
  tests/unit/info.tcl
  tests/unit/latency-monitor.tcl
Labels: action:run-benchmark, 7.0-must-have

#10092 Set repl-diskless-sync to yes by default, add repl-diskless-sync-max-replicas
  redis.conf
  src/config.c
  src/networking.c
  src/replication.c
  src/server.h
  tests/assets/default.conf
  tests/cluster/tests/05-slave-selection.tcl
  tests/cluster/tests/06-slave-stop-cond.tcl
  tests/cluster/tests/14-consistency-check.tcl
  tests/instances.tcl
  tests/integration/replication-2.tcl
  tests/integration/replication-4.tcl
  tests/integration/replication-buffer.tcl
  tests/integration/replication.tcl
  tests/support/util.tcl
  tests/unit/moduleapi/hooks.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-RC1-must-have

#10131 Fix `FUNCTION LOAD` ignores unknown parameter.
  src/functions.c
  tests/unit/functions.tcl
Labels: class:bug

#10110 Fix additional AOF filename issues.
  src/aof.c
  src/config.c
  src/sds.c
  src/sds.h
  src/util.c
  src/util.h
  tests/integration/aof-multi-part.tcl
Labels: 7.0-RC1-must-have

#10001 Add event loop support to the module API
  runtest-moduleapi
  src/ae.c
  src/ae.h
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/eventloop.c
  tests/unit/moduleapi/eventloop.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#10145 Fix fcall_ro key spec flags in commands.c
  src/commands.c
  utils/generate-command-code.py
Labels: state:to-be-merged

#10141 Added AOF rewrite support for functions.
  src/aof.c
  tests/unit/aofrw.tcl
Labels: 7.0-RC1-must-have

#9963 Adding module api for processing commands during busy jobs and allow flagging the commands that should be handled at this status
  redis.conf
  src/blocked.c
  src/commands.c
  src/commands/auth.json
  src/commands/discard.json
  src/commands/function-kill.json
  src/commands/function-stats.json
  src/commands/hello.json
  src/commands/multi.json
  src/commands/quit.json
  src/commands/replicaof.json
  src/commands/reset.json
  src/commands/script-kill.json
  src/commands/shutdown.json
  src/commands/unwatch.json
  src/commands/watch.json
  src/config.c
  src/db.c
  src/eval.c
  src/module.c
  src/networking.c
  src/redismodule.h
  src/script.c
  src/script_lua.c
  src/server.c
  src/server.h
  tests/modules/blockedclient.c
  tests/modules/datatype.c
  tests/unit/functions.tcl
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/moduleapi/datatype.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-RC1-must-have

#10154 Added functions support to redis-check-rdb
  src/rdb.c
  src/redis-check-rdb.c
Labels: 7.0-RC1-must-have

#10147 Improved handling of subcommands (don't allow ACL on first-arg of a sub-command)
  src/acl.c
  src/server.c
  tests/unit/acl.tcl
  tests/unit/introspection-2.tcl
Labels: release-notes, 7.0-RC1-must-have

#10127 sub-command support for ACL CAT and COMMAND LIST. redisCommand always stores fullname
  src/acl.c
  src/cluster.c
  src/expire.c
  src/latency.c
  src/module.c
  src/networking.c
  src/sentinel.c
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_list.c
  src/t_stream.c
  src/t_string.c
  src/t_zset.c
  tests/modules/auth.c
  tests/modules/propagate.c
  tests/modules/subcommands.c
  tests/sentinel/tests/03-runtime-reconf.tcl
  tests/support/test.tcl
  tests/unit/acl.tcl
  tests/unit/expire.tcl
  tests/unit/functions.tcl
  tests/unit/info.tcl
  tests/unit/introspection-2.tcl
  tests/unit/introspection.tcl
  tests/unit/latency-monitor.tcl
  tests/unit/moduleapi/aclcheck.tcl
  tests/unit/moduleapi/auth.tcl
  tests/unit/moduleapi/basics.tcl
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/moduleapi/commandfilter.tcl
  tests/unit/moduleapi/eventloop.tcl
  tests/unit/moduleapi/fork.tcl
  tests/unit/moduleapi/getkeys.tcl
  tests/unit/moduleapi/hash.tcl
  tests/unit/moduleapi/infotest.tcl
  tests/unit/moduleapi/infra.tcl
  tests/unit/moduleapi/keyspace_events.tcl
  tests/unit/moduleapi/keyspecs.tcl
  tests/unit/moduleapi/list.tcl
  tests/unit/moduleapi/misc.tcl
  tests/unit/moduleapi/propagate.tcl
  tests/unit/moduleapi/reply.tcl
  tests/unit/moduleapi/scan.tcl
  tests/unit/moduleapi/stream.tcl
  tests/unit/moduleapi/subcommands.tcl
  tests/unit/moduleapi/timer.tcl
  tests/unit/moduleapi/zset.tcl
  tests/unit/pause.tcl
  tests/unit/type/hash.tcl
  tests/unit/type/list.tcl
  tests/unit/type/set.tcl
  tests/unit/type/stream.tcl
  tests/unit/type/string.tcl
  tests/unit/type/zset.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-RC1-must-have

#10036 Fix timing issue in sentinel CKQUORUM test
  tests/sentinel/tests/06-ckquorum.tcl
Labels: state:to-be-merged

#10157 Fix flaky cluster tests in 24-links.tcl
  tests/cluster/tests/24-links.tcl
Labels: 7.0-RC1-must-have

#10135 Disable keyspec module API in 7.0 RC1
  src/module.c
  src/redismodule.h
  tests/modules/keyspecs.c
  tests/modules/subcommands.c
  tests/unit/moduleapi/keyspecs.tcl
  tests/unit/moduleapi/subcommands.tcl
Labels: 7.0-RC1-must-have

#10126 Support function flags in script EVAL via shebang header
  src/commands.c
  src/commands/eval.json
  src/commands/eval_ro.json
  src/commands/evalsha.json
  src/commands/evalsha_ro.json
  src/commands/script-load.json
  src/eval.c
  src/functions.c
  src/script.c
  src/script.h
  src/server.c
  src/server.h
  tests/cluster/tests/00-base.tcl
  tests/unit/functions.tcl
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-RC1-must-have

#10166 Fix outdated save key word in redis.conf
  redis.conf
Labels: state:to-be-merged, class:text

#10167 Improve testing and update flags around commands without ACL keyspec flags
  src/commands.c
  src/commands/pfcount.json
  src/commands/sintercard.json
  src/commands/sismember.json
  src/commands/zcount.json
  src/commands/zintercard.json
  tests/unit/acl-v2.tcl
Labels: state:major-decision, 7.0-RC1-must-have

#10179 Added engine stats to FUNCTION STATS command.
  src/functions.c
  tests/unit/functions.tcl
Labels: 7.0-RC1-must-have

#10184 Fix unused variable warning in subcommand.c
  tests/modules/subcommands.c
Labels: state:to-be-merged

#10148 Allow SET without GET arg on write-only ACL. Allow BITFIELD GET on read-only ACL
  src/commands.c
  src/commands/bitfield.json
  src/commands/set.json
  src/db.c
  src/server.h
  tests/unit/acl-v2.tcl
  tests/unit/moduleapi/aclcheck.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-RC1-must-have

#10199 doc improvement about acl first-arg
  redis.conf
Labels: 7.0-RC1-must-have

#10146 Fixed Sentinel support for hostnames and dynamic IP addresses
  src/sentinel.c
Labels: release-notes

#10208 Fix some wrong commands arguments since
  src/commands.c
  src/commands/georadius_ro.json
  src/commands/shutdown.json
  src/commands/zadd.json
Labels: state:to-be-merged

#10193 Add key-specs notes
  src/commands.c
  src/commands/bitfield.json
  src/commands/eval.json
  src/commands/eval_ro.json
  src/commands/fcall.json
  src/commands/fcall_ro.json
  src/commands/getex.json
  src/commands/pfcount.json
  src/commands/set.json
  src/commands/sort.json
  src/commands/sort_ro.json
  src/commands/xadd.json
  src/db.c
  src/server.c
  src/server.h
  utils/generate-command-code.py
Labels: 7.0-RC1-must-have

#10181 Set default channel permission to resetchannels for 7.0
  redis.conf
  src/config.c
  tests/assets/user.acl
  tests/unit/acl-v2.tcl
  tests/unit/acl.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, breaking-change, 7.0-RC1-must-have

#10197 Add entropy to srand (and fix Sentinel failures)
  src/server.c
Labels: release-notes, 7.0-must-have

#10206 Resize notused1 in clusterMsg so that clusterMsg is backward compatible with previous Redis releases
  src/ae_evport.c
  src/cluster.h
  src/server.h
Labels: 7.0-RC1-must-have

#10210 update help.h before release
  src/help.h
Labels: 7.0-RC1-must-have
