Repository redis/redis, pull requests merged in 2022-09, with the labels that each got.

#11238 Fix typo in DEBUG REPLYBUFFER RESIZING comment
  src/debug.c
Labels: class:text

#11141 Update comment describing ziplist example to use documented names
  src/ziplist.c
Labels: class:text

#11244 Optimize setGenericCommand(): no need to remove the expiration entry when 'expire' is not NULL
  src/t_string.c
Labels: state:to-be-merged

#11263 Avoid crash when a cluster node is a replica of a replica of itself
  src/cluster.c
Labels: release-notes

#11220 Adds listnode to client struct for clients_pending_write list
  src/adlist.c
  src/adlist.h
  src/module.c
  src/networking.c
  src/server.h
Labels: release-notes

#11237 fix infinite sleep in performEvictions when have lazyfree jobs
  src/evict.c
Labels: release-notes

#11151 Fix Invalid node address specified in redis-cli --cluster create/add-node
  src/redis-cli.c
Labels: release-notes

#11291 Fix missing sections for INFO ALL with module
  src/server.c
  tests/unit/moduleapi/infotest.tcl
Labels: release-notes

#11279 ACL default newly created user set USER_FLAG_SANITIZE_PAYLOAD flag
  redis.conf
  src/acl.c
  tests/unit/acl.tcl
Labels: state:major-decision

#10966 Add RM_SetContextUser to support acl validation in RM_Call (and scripts)
  runtest-moduleapi
  src/acl.c
  src/config.c
  src/module.c
  src/networking.c
  src/redismodule.h
  src/server.h
  tests/modules/Makefile
  tests/modules/usercall.c
  tests/unit/moduleapi/usercall.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change

#11297 Fix CLUSTER SHARDS showing empty hostname
  src/cluster.c
Labels: release-notes

#11319 Ignore RM_Call deny-oom flag if maxmemory is zero
  src/module.c
  tests/unit/moduleapi/misc.tcl
Labels: release-notes

#11269 fix: redis-cli --memkeys-samples add check lastarg
  src/redis-cli.c
Labels: state:to-be-merged

#11341 Update CLUSTER NODES help message
  src/cluster.c
Labels: class:text
