Repository redis/redis, pull requests merged in 2022-10, with the labels that each got.

#11280 code, typo and comment cleanups
  src/cluster.c
  src/commands.c
  src/commands/cluster-getkeysinslot.json
  src/rax.c
  src/replication.c
  src/server.h
  src/tracking.c
Labels: class:text

#11207 Change compiler optimizations to -O3 -flto
  src/Makefile
  src/bitops.c
  src/t_stream.c
Labels: action:run-benchmark

#11335 register debug support on illumos/solaris.
  src/Makefile
  src/config.h
  src/debug.c
Labels: release-notes

#11307 Stabilize cluster hostnames tests
  src/cluster.c
  src/config.c
  src/server.h
  tests/support/cluster_helper.tcl
  tests/support/server.tcl
  tests/unit/cluster/hostnames.tcl
Labels: state:major-decision, approval-needed

#11350 Pass -flto flag to the linker
  src/Makefile
  src/quicklist.c
  src/t_zset.c
Labels: action:run-benchmark

#11288 Added authentication failure and access denied metrics
  src/acl.c
  src/server.c
  src/server.h
  tests/unit/acl.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#11364 Fix non-existent directive name in redis.conf comments
  redis.conf
Labels: class:text

#11268 `RedisModule_ResetDataset` should not clear the functions.
  src/module.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, approval-needed, breaking-change

#10300 Freeze time sampling during command execution, and scripts
  src/acl.c
  src/blocked.c
  src/cluster.c
  src/db.c
  src/expire.c
  src/module.c
  src/replication.c
  src/server.c
  src/server.h
  src/t_stream.c
  src/t_string.c
  src/timeout.c
  tests/unit/scripting.tcl
Labels: state:major-decision, release-notes, breaking-change

#11372 Update outdated commands descriptions and cleanups in README
  README.md
Labels: class:text

#11253 MIGTATE with AUTH that contains "keys" is getting wrong key names in migrateGetKeys, leads to ACL errors
  src/db.c
  tests/unit/acl-v2.tcl
Labels: state:needs-review, release-notes

#10587 optimizing d2string() and addReplyDouble() with grisu2: double to string conversion based on Florian Loitsch's Grisu-algorithm
  .gitignore
  deps/Makefile
  deps/fpconv/LICENSE.txt
  deps/fpconv/Makefile
  deps/fpconv/README.md
  deps/fpconv/fpconv_dtoa.c
  deps/fpconv/fpconv_dtoa.h
  deps/fpconv/fpconv_powers.h
  src/Makefile
  src/debug.c
  src/networking.c
  src/rdb.c
  src/rio.c
  src/script_lua.c
  src/util.c
  src/util.h
  tests/integration/rdb.tcl
  tests/unit/type/zset.tcl
Labels: release-notes, action:run-benchmark

#11160 Unify ACL failure error messaging.
  src/acl.c
  src/module.c
  src/script.c
  src/server.c
  src/server.h
  tests/unit/acl-v2.tcl
  tests/unit/acl.tcl
  tests/unit/moduleapi/aclcheck.tcl
  tests/unit/moduleapi/getkeys.tcl
  tests/unit/moduleapi/keyspecs.tcl
  tests/unit/moduleapi/misc.tcl
  tests/unit/moduleapi/usercall.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change

#11374 Avoid saving module aux on RDB if no aux data was saved by the module.
  src/module.c
  src/rdb.c
  src/rdb.h
  src/redismodule.h
  src/server.h
  tests/modules/testrdb.c
  tests/unit/moduleapi/testrdb.tcl
Labels: state:major-decision, release-notes, approval-needed

#11425 RM_Call - only enforce OOM on scripts if 'M' flag is sent
  src/module.c
  src/script.c
  src/server.h
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, release-notes, breaking-change
