Repository redis/redis, pull requests merged in 2022-06, with the labels that each got.

#10786 Fix broken protocol in MISCONF error, RM_Yield bugs, RM_Call(EVAL) OOM check bug, and new RM_Call checks.
  src/call_reply.c
  src/db.c
  src/evict.c
  src/module.c
  src/networking.c
  src/script.c
  src/server.c
  src/server.h
  tests/integration/rdb.tcl
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
  tests/unit/scripting.tcl
Labels: 7.0-must-have

#10744 Expose script flags to processCommand for better handling
  src/aof.c
  src/eval.c
  src/functions.c
  src/multi.c
  src/script.c
  src/script.h
  src/server.c
  src/server.h
  tests/unit/functions.tcl
  tests/unit/moduleapi/misc.tcl
  tests/unit/pause.tcl
  tests/unit/scripting.tcl
Labels: breaking-change, 7.0-must-have

#10761 Fix bugs in CONFIG REWRITE, omitting rename-command and include lines, and inserting comments around module and acl configs
  src/config.c
  tests/unit/acl.tcl
  tests/unit/introspection.tcl
Labels: 7.0-must-have

#10808 Only print final log when aof is loaded successfully
  src/server.c
Labels: 7.0-must-have

#10811 rewrite alias config to original name
  src/config.c
  tests/unit/introspection.tcl
Labels: 7.0-must-have

#9759 Update time independent string compare to use hash length
  src/acl.c
  src/server.h
Labels: state:to-be-merged

#10812 some minor spelling/grammatical fixes to module.c
  src/module.c
Labels: state:to-be-merged

#10810 Split instantaneous_repl_total_kbps
  src/server.c
  src/server.h
Labels: 7.0-must-have

#10822 Handle multiple_token flag in generate-command-help.rb
  src/commands.c
  src/commands/bitfield.json
  src/commands/bitfield_ro.json
  src/help.h
  utils/generate-command-help.rb
Labels: state:to-be-merged

#10848 Fix crash when overcommit_memory is inaccessible
  src/server.c
  src/syscheck.c
Labels: release-notes, 7.0-must-have

#10837 Fixed SET and BITFIELD commands being wrongly marked movablekeys
  src/module.c
  src/server.c
  src/server.h
  tests/modules/keyspecs.c
  tests/unit/introspection-2.tcl
  tests/unit/moduleapi/keyspecs.tcl
Labels: release-notes, 7.0-must-have

#10844 Fix 3 comments in server.c
  src/server.c
Labels: class:text

#10841 Correctly check for vm.overcommit_memory == 0
  src/syscheck.c
Labels: 7.0-must-have

#9526 Throw -TRYAGAIN instead of -ASK on migrating nodes for multi-key commands when the node only has some of the keys
  src/cluster.c
Labels: release-notes, 7.0-must-have

#10860 Fix 2 comments in dict.c & redis-cli.c
  src/dict.c
  src/redis-cli.c
Labels: class:text

#10853 Allow ECHO in loading and stale modes
  src/commands.c
  src/commands/echo.json
  tests/unit/scripting.tcl
Labels: release-notes

#10855 Script that made modification will not break with unexpected NOREPLICAS error
  src/script.c
  tests/unit/scripting.tcl
Labels: release-notes

#10737 Fsync directory while persisting AOF manifest, RDB file, and config file
  src/aof.c
  src/config.c
  src/rdb.c
  src/replication.c
  src/util.c
  src/util.h
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10624 optimize the performance of clusterSendPing
  src/cluster.c
  src/cluster.h
Labels: release-notes

#10886 Fix crash on RM_Call with script mode.
  src/module.c
  tests/modules/blockedclient.c
  tests/unit/moduleapi/blockedclient.tcl
Labels: 7.0-must-have

#10891 fix redis-benchmark's bug: check if clients are created successfully in idle mode
  src/redis-benchmark.c
  tests/integration/redis-benchmark.tcl
Labels: approval-needed

#10304 Add bus_port argument in cluster-meet.json
  src/commands.c
  src/commands/cluster-meet.json
Labels: state:to-be-merged

#10097 changing min,max in ZRANGE -> start stop
  src/commands.c
  src/commands/zrange.json
Labels: state:needs-doc-pr, state:to-be-merged

#10839 Add RM_SetClientNameById and RM_GetClientNameById
  src/module.c
  src/networking.c
  src/redismodule.h
  src/server.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, release-notes, approval-needed

#10866 redis-server command line arguments allow passing config name and value in the same arg
  src/server.c
  tests/unit/introspection.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10889 Support conversion between `RedisModuleString` and `unsigned long long`
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, release-notes, approval-needed

#10885 Add missing REDISMODULE_CLIENTINFO_INITIALIZER
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
Labels: 7.0-must-have

#10895 Add sharded pubsub keychannel count to client info
  src/networking.c
  tests/unit/introspection.tcl
Labels: state:major-decision, approval-needed
