Repository redis/redis, pull requests merged in 2022-07, with the labels that each got.

#10912 Unlock cluster config file upon server shutdown
  src/cluster.c
  src/server.c
Labels: state:to-be-merged, release-notes

#10931 TLS: Notify clients on connection shutdown.
  src/tls.c
Labels: release-notes

#10929 Add pubsubshard_channels field in INFO STATS
  src/server.c
  src/server.h
Labels: state:needs-doc-pr, approval-needed

#10946 Fix some outdated comments and some typo
  redis.conf
  src/functions.c
  src/listpack.c
  src/rdb.c
  src/server.c
  src/server.h
Labels: class:text

#10942 Fix crash during handshake and cluster shards call
  src/cluster.c
  tests/cluster/tests/28-cluster-shards.tcl
Labels: release-notes

#10344 Add cluster-port support to redis-cli --cluster
  src/redis-cli.c
  tests/support/util.tcl
  tests/unit/cluster.tcl
Labels: state:major-decision, release-notes, approval-needed

#10924 Make cluster config file saving atomic and fsync acl
  src/acl.c
  src/cluster.c
Labels: release-notes

#10696 Don't update node ip when peer ip is unreachable
  src/cluster.c
  src/connection.c
Labels: release-notes

#10869 Gossip forgotten nodes on `CLUSTER FORGET`
  src/cluster.c
  src/cluster.h
  tests/unit/cluster/hostnames.tcl
Labels: state:major-decision, release-notes, approval-needed

#11032 Fix #11030, use lua_rawget to avoid triggering metatables and crash.
  src/script_lua.c
  tests/unit/scripting.tcl
Labels: state:major-decision

#11038 When client tracking is on, invalidation message of flushdb in a
  src/tracking.c
  tests/unit/tracking.tcl
Labels: release-notes

#11050 Optimization: moduleLoadString should try to create embedded string
  src/rdb.c
Labels: release-notes
