Repository redis/redis, pull requests merged in 2022-03, with the labels that each got.

#10359 acl dryrun should return the command if the user doesn't have access to it
  src/acl.c
  tests/unit/acl-v2.tcl
Labels: release-notes

#10323 Move most of the configuration to a hashtable
  src/config.c
  src/server.c
  src/server.h
Labels: release-notes

#5539 A faster and more robust code of zslRandomLevel using RAND_MAX
  src/t_zset.c
Labels: state:to-be-merged

#10376 Constrain cluster node name logging
  src/cluster.c
Labels: state:to-be-merged

#10286 Escape string for JSON output(--json)
  src/cli_common.c
  src/cli_common.h
  src/redis-cli.c
  tests/integration/redis-cli.tcl
Labels: release-notes, 7.0-must-have

#10388 Fix timing issue in rehash test
  tests/unit/other.tcl
Labels: state:to-be-merged

#10311 Add a Config Change Event for Redis Modules
  src/config.c
  src/module.c
  src/redismodule.h
  tests/modules/hooks.c
  tests/unit/moduleapi/hooks.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#10387 Add missing doc_flags to cluster-slaves
  src/commands.c
  src/commands/cluster-slaves.json
Labels: state:to-be-merged

#10393 Fix redis-benchmark --cluster with IPv6.
  src/redis-benchmark.c
Labels: release-notes

#10364 script should not allow may-replicate commands when client pause write
  src/script.c
  tests/unit/pause.tcl
Labels: 7.0-must-have

#10396 Update redis.conf
  redis.conf
Labels: class:text

#10399 Fix typo "the the"
  .github/workflows/codeql-analysis.yml
  src/cli_common.c
  src/defrag.c
  src/module.c
  src/server.h
  src/ziplist.c
  tests/unit/memefficiency.tcl
Labels: class:text

#10402 fix typos
  src/defrag.c
  src/listpack.c
  src/localtime.c
  src/networking.c
  src/rax.c
  src/server.c
  src/ziplist.c
Labels: class:text

#10394 Fix outdated comments on updateSlavesWaitingBgsave
  src/replication.c
Labels: class:text

#10382 Initialize help when using redis-cli help or redis-cli ?
  src/redis-cli.c
Labels: state:to-be-merged

#10424 Fix timing issue in sentinel reconnect test
  tests/sentinel/tests/03-runtime-reconf.tcl
Labels: state:to-be-merged

#10401 Optimization: remove `updateClientMemUsage` from i/o threads.
  src/networking.c
  src/server.c
  src/server.h
Labels: action:run-benchmark

#10340 make sort/ro commands validate external keys access patterns (#10106)
  src/acl.c
  src/server.h
  src/sort.c
  tests/unit/acl-v2.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#10425 Add module API for redacting command arguments
  src/module.c
  src/networking.c
  src/redismodule.h
  tests/modules/auth.c
  tests/unit/moduleapi/auth.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10293 Add cluster shards support.
  src/cluster.c
  src/cluster.h
  src/commands.c
  src/commands/cluster-shards.json
  src/commands/cluster-slots.json
  tests/cluster/cluster.tcl
  tests/cluster/tests/27-endpoints.tcl
  tests/cluster/tests/28-cluster-shards.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-must-have

#10432 Fix module redact test for valgrind
  tests/unit/moduleapi/auth.tcl
Labels: state:to-be-merged

#10435 Fixed incorrect parsing of hostname information from nodes.conf
  src/cluster.c
  tests/cluster/tests/27-endpoints.tcl
Labels: release-notes

#10274 fix wrong comment about cluster_announce_hostname
  src/server.h
Labels: class:text

#10450 Fix timing issue in shards test and fix displayed TLS port
  src/cluster.c
  tests/cluster/tests/28-cluster-shards.tcl
Labels: 7.0-must-have

#10372 Add new RM_Call flags for script mode, no writes, and error replies.
  src/acl.c
  src/call_reply.c
  src/call_reply.h
  src/module.c
  src/replication.c
  src/script.c
  src/server.c
  src/server.h
  tests/modules/aclcheck.c
  tests/modules/basics.c
  tests/modules/blockedclient.c
  tests/unit/moduleapi/aclcheck.tcl
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/moduleapi/cluster.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#10452 Cleanups in redis.conf
  redis.conf
Labels: class:text

#10302 show cluster.links in MEMORY STATS
  src/object.c
Labels: state:needs-doc-pr

#10436 redis-cli: Do DNS lookup before sending CLUSTER MEET
  src/redis-cli.c
Labels: release-notes, 7.0-must-have

#10473 command json files cleanups
  src/commands.c
  src/commands/cluster-shards.json
  src/commands/cluster-slots.json
  src/commands/command-docs.json
  src/commands/command-getkeysandflags.json
  src/commands/command-info.json
  src/commands/command-list.json
  src/commands/command.json
  src/commands/function-list.json
  src/commands/latency-doctor.json
  src/commands/latency-graph.json
  src/commands/latency-history.json
  src/commands/memory-doctor.json
  src/commands/memory-malloc-stats.json
  src/commands/memory-purge.json
  src/commands/migrate.json
  src/commands/module-list.json
  src/commands/msetnx.json
  src/commands/object-refcount.json
  src/commands/psync.json
  src/commands/pubsub-channels.json
  src/commands/pubsub-shardchannels.json
  src/commands/pubsub-shardnumsub.json
  src/commands/replicaof.json
  src/commands/sentinel-config.json
  src/commands/sentinel-reset.json
  src/commands/slaveof.json
  src/commands/sort.json
  src/commands/sort_ro.json
  src/commands/spublish.json
  src/commands/ssubscribe.json
  src/commands/sunsubscribe.json
Labels: 7.0-must-have

#10285 Module Configurations
  runtest-moduleapi
  src/commands.c
  src/commands/module-loadex.json
  src/config.c
  src/module.c
  src/redismodule.h
  src/sentinel.c
  src/server.h
  src/util.h
  tests/modules/Makefile
  tests/modules/moduleconfigs.c
  tests/modules/moduleconfigstwo.c
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#10497 Move restart_killed_instances and verify_sentinel_auto_discovery to utils
  tests/sentinel/tests/08-hostname-conf.tcl
  tests/sentinel/tests/includes/init-tests.tcl
  tests/sentinel/tests/includes/utils.tcl
Labels: state:to-be-merged

#10468 Use exit code 1 on error in redis-cli
  src/redis-cli.c
Labels: release-notes

#10495 Fix cluster slot migration test
  tests/unit/cluster.tcl
Labels: 7.0-must-have
