Repository redis/redis, pull requests merged in 2022-08, with the labels that each got.

#11092 fix typos around dict funtions of cstring
  src/server.c
Labels: class:text

#11108 Fix outdated lfu-decay-time doc in redis.conf
  redis.conf
Labels: class:text

#11058 Trim rdb loading code for pre-release formats
  src/functions.c
  src/module.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/server.h
Labels: state:major-decision, approval-needed

#10969 Fix replication inconsistency on modules that uses key space notifications
  src/aof.c
  src/db.c
  src/debug.c
  src/evict.c
  src/expire.c
  src/module.c
  src/replication.c
  src/server.c
  src/server.h
  src/t_set.c
  tests/modules/keyspace_events.c
  tests/unit/expire.tcl
  tests/unit/maxmemory.tcl
  tests/unit/moduleapi/propagate.tcl
  tests/unit/multi.tcl
Labels: state:major-decision

#11059 Support setlocale via CONFIG operation.
  redis.conf
  src/config.c
  src/server.c
  src/server.h
Labels: state:major-decision, release-notes, approval-needed, interface-change

#11093 [PERF] use snprintf once in addReplyDouble
  src/networking.c
Labels: action:run-benchmark

#9320 Fully abstract connection and make TLS dynamically loadable
  .github/workflows/ci.yml
  .github/workflows/daily.yml
  TLS.md
  deps/Makefile
  src/Makefile
  src/anet.c
  src/anet.h
  src/cluster.c
  src/config.c
  src/connection.c
  src/connection.h
  src/mkreleasehdr.sh
  src/module.c
  src/networking.c
  src/redis-cli.c
  src/redismodule.h
  src/release.c
  src/replication.c
  src/sentinel.c
  src/server.c
  src/server.h
  src/socket.c
  src/tls.c
  src/unix.c
  tests/instances.tcl
  tests/modules/defragtest.c
  tests/support/server.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/moduleapi/infra.tcl
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: state:major-decision, release-notes, approval-needed, interface-change

#11176 Fix assertion when a key is lazy expired during cluster key migration
  src/cluster.c
  src/db.c
  src/server.h
  tests/test_helper.tcl
  tests/unit/cluster/misc.tcl
Labels: approval-needed

#11192 Improve error message
  src/networking.c
Labels: class:text
