Repository redis/redis, pull requests merged in 2022-02, with the labels that each got.

#10160 Add check min-slave-* feature when evaluating Lua scripts and Functions
  src/script.c
  tests/integration/replication-4.tcl
Labels: release-notes, 7.0-must-have

#10151 Sentinel: return an error if configuration save fails
  src/sentinel.c
  tests/sentinel/tests/03-runtime-reconf.tcl
Labels: release-notes

#10231 Fix cluster tests failing due to subcommand names
  tests/cluster/tests/23-multiple-slot-operations.tcl
Labels: state:to-be-merged

#10108 Command info module API
  runtest-moduleapi
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/cmdintrospection.c
  tests/modules/keyspecs.c
  tests/modules/subcommands.c
  tests/unit/moduleapi/cmdintrospection.tcl
  tests/unit/moduleapi/keyspecs.tcl
  tests/unit/moduleapi/subcommands.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10240 Update FCALL/FCALL_RO summary and complexity
  src/commands.c
  src/commands/fcall.json
  src/commands/fcall_ro.json
  src/help.h
Labels: state:to-be-merged

#10043 redis-cli generates command help tables from the results of COMMAND
  src/redis-cli.c
  tests/support/util.tcl
  utils/generate-command-help.rb
Labels: 7.0-must-have

#4241 Fix file descriptor leak
  src/debug.c
Labels: state:to-be-merged

#10223 create-cluster clean now will clean appendonlydir
  utils/create-cluster/create-cluster
Labels: state:to-be-merged, 7.0-must-have

#10220 acl check api for functions and eval
  src/script_lua.c
  src/server.h
  tests/unit/scripting.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed, 7.0-must-have

#10250 Fix redis-cli with sentinel crash due to SENTINEL DEBUG missing summary
  src/commands.c
  src/commands/sentinel-debug.json
  src/sentinel.c
Labels: state:to-be-merged

#10237 Handle key-spec flags with modules
  src/commands.c
  src/commands/command-getkeysandflags.json
  src/db.c
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/modules/getkeys.c
  tests/modules/keyspecs.c
  tests/unit/introspection-2.tcl
  tests/unit/moduleapi/getkeys.tcl
  tests/unit/moduleapi/keyspecs.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10227 X[AUTO]CLAIM should skip deleted entries
  src/commands.c
  src/commands/xautoclaim.json
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: state:major-decision, release-notes, breaking-change, 7.0-must-have

#10218 Consistent erros returned from EVAL scripts
  src/script_lua.c
  tests/unit/scripting.tcl
Labels: state:needs-test-code, 7.0-must-have

#6891 Make INFO command variadic
  src/commands.c
  src/commands/info.json
  src/debug.c
  src/module.c
  src/sentinel.c
  src/server.c
  src/server.h
  tests/sentinel/tests/13-info-command.tcl
  tests/test_helper.tcl
  tests/unit/info-command.tcl
  tests/unit/moduleapi/infotest.tcl
Labels: state:major-decision, release-notes, approval-needed, 7.0-must-have

#10248 Remove assert and refuse delete expired on ro replicas
  src/db.c
Labels: 7.0-must-have

#10265 Attempt to fix a rare crash in cluster tests.
  src/replication.c
Labels: state:to-be-merged

#10268 Fix INFO SENTINEL memory leak
  src/sentinel.c
  tests/sentinel/tests/13-info-command.tcl
Labels: state:to-be-merged

#4687 Fix the misleading description of the option repl-ping-slave-period
  redis.conf
Labels: state:to-be-merged

#10271 Fix Eval scripts defrag (broken 7.0 in RC1)
  src/defrag.c
  src/eval.c
  src/server.h
  tests/unit/memefficiency.tcl
Labels: 7.0-must-have

#10278 Fix and improve module error reply statistics
  src/call_reply.c
  src/call_reply.h
  src/module.c
  src/networking.c
  src/server.h
  tests/unit/moduleapi/blockedclient.tcl
Labels: 7.0-must-have

#10291 Fix OpenSSL 3.0.x related issues.
  redis.conf
  src/tls.c
Labels: release-notes

#10061 Adapt redis-check-aof tool for Multi Part Aof
  src/aof.c
  src/redis-check-aof.c
  tests/integration/aof-multi-part.tcl
  tests/integration/aof.tcl
Labels: release-notes, 7.0-must-have

#10178 aof rewrite and rdb save counters in info
  src/aof.c
  src/rdb.c
  src/server.c
  src/server.h
Labels: state:needs-doc-pr, release-notes, 7.0-must-have

#10314 Show publishshard_sent stat in cluster info
  redis.conf
  src/cluster.c
  src/cluster.h
Labels: state:needs-doc-pr, state:to-be-merged

#10312 Fix a mistake in comments
  src/replication.c
Labels: class:text

#10018 Fix geo search bounding box check causing missing results
  src/geohash_helper.c
  tests/unit/geo.tcl
Labels: state:to-be-merged, release-notes

#10315 Remove ALLOW_BUSY from REPLICAOF and add it to REPLCONF. Add DEPRECATED doc flag to SLAVEOF, mark it as deprecated.
  src/commands.c
  src/commands/replconf.json
  src/commands/replicaof.json
  src/commands/slaveof.json
Labels: state:to-be-merged

#10299 Implemented module getchannels api and renamed channel keyspec
  src/acl.c
  src/commands.c
  src/commands/spublish.json
  src/commands/ssubscribe.json
  src/commands/sunsubscribe.json
  src/db.c
  src/module.c
  src/redismodule.h
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/aclcheck.c
  tests/modules/getchannels.c
  tests/unit/moduleapi/aclcheck.tcl
  tests/unit/moduleapi/getchannels.tcl
Labels: state:major-decision, release-notes, 7.0-must-have

#9822 introduce dynamic client reply buffer size - save memory on idle clients
  src/debug.c
  src/networking.c
  src/server.c
  src/server.h
  tests/test_helper.tcl
  tests/unit/client-eviction.tcl
  tests/unit/introspection.tcl
  tests/unit/replybufsize.tcl
Labels: state:major-decision, release-notes, action:run-benchmark, 7.0-must-have

#10256 Delete key doesn't dirty client who watched stale key
  src/db.c
  src/multi.c
  tests/unit/multi.tcl
Labels: release-notes, 7.0-must-have

#9934 Reduce system calls of write for client->reply by introducing writev
  src/connection.c
  src/connection.h
  src/networking.c
  src/tls.c
Labels: action:run-benchmark, 7.0-must-have

#10332 Fix timing issue in EXEC fail on lazy expired WATCHed key test
  tests/unit/multi.tcl
Labels: state:to-be-merged

#9127 Add stream consumer group lag tracking and reporting
  src/aof.c
  src/cluster.c
  src/commands.c
  src/commands/xgroup-create.json
  src/commands/xgroup-setid.json
  src/commands/xinfo-groups.json
  src/commands/xinfo-stream.json
  src/commands/xsetid.json
  src/rdb.c
  src/rdb.h
  src/server.c
  src/server.h
  src/stream.h
  src/t_stream.c
  tests/integration/corrupt-dump.tcl
  tests/unit/type/stream-cgroups.tcl
  tests/unit/type/stream.tcl
Labels: state:major-decision, 7.0-must-have

#10339 Fix XGROUP HELP message missing a newline
  src/t_stream.c
Labels: state:to-be-merged

#10297 Update deps/hiredis to latest version.
  deps/hiredis/.github/workflows/build.yml
  deps/hiredis/.travis.yml
  deps/hiredis/CHANGELOG.md
  deps/hiredis/CMakeLists.txt
  deps/hiredis/Makefile
  deps/hiredis/README.md
  deps/hiredis/adapters/libev.h
  deps/hiredis/adapters/libevent.h
  deps/hiredis/adapters/libuv.h
  deps/hiredis/async.c
  deps/hiredis/async.h
  deps/hiredis/dict.c
  deps/hiredis/dict.h
  deps/hiredis/examples/CMakeLists.txt
  deps/hiredis/examples/example-libuv.c
  deps/hiredis/examples/example-push.c
  deps/hiredis/examples/example-ssl.c
  deps/hiredis/examples/example.c
  deps/hiredis/fmacros.h
  deps/hiredis/fuzzing/format_command_fuzzer.c
  deps/hiredis/hiredis.c
  deps/hiredis/hiredis.h
  deps/hiredis/hiredis.targets
  deps/hiredis/hiredis_ssl.h
  deps/hiredis/read.c
  deps/hiredis/sds.c
  deps/hiredis/ssl.c
  deps/hiredis/test.c
Labels: 7.0-must-have

#10337 Optimization: Avoid deferred array reply on ZRANGE commands BYRANK
  src/networking.c
  src/t_zset.c
Labels: action:run-benchmark

#10335 Enable redis-benchmark to use RESP3 protocol mode
  src/redis-benchmark.c
Labels: release-notes

#10329 Sort out the mess around Lua error messages and error stats
  src/eval.c
  src/function_lua.c
  src/module.c
  src/multi.c
  src/networking.c
  src/script.c
  src/script_lua.c
  src/script_lua.h
  src/server.c
  src/server.h
  tests/unit/introspection-2.tcl
  tests/unit/scripting.tcl
Labels: release-notes, 7.0-must-have

#10351 Make git ignore all files starting with appendonly.aof
  .gitignore
Labels: state:to-be-merged

#10348 Fix node-id type in cluster-setslot
  src/cluster.c
  src/commands.c
  src/commands/cluster-setslot.json
Labels: state:to-be-merged
