Repository redis/redis, pull requests merged in 2023-08, with the labels that each got.

#12452 fix false success and a memory leak for ACL selector with bad parenthesis combination
  src/acl.c
  tests/unit/acl-v2.tcl
Labels: release-notes

#12476 Add two stats to count client input and output buffer oom.
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/info.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes

#12486 Allows modules to declare new ACL categories.
  src/acl.c
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/aclcheck.c
  tests/unit/moduleapi/aclcheck.tcl
Labels: state:major-decision, release-notes, approval-needed

#12450 Optimize ZRANGE offset location from linear search to skiplist jump.
  src/geo.c
  src/module.c
  src/server.h
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: action:run-benchmark
