Repository redis/redis, pull requests merged in 2023-11, with the labels that each got.

#12536 Optimize SCAN with MATCH when pattern implies cluster slot
  src/cluster.c
  src/cluster.h
  src/db.c
  src/expire.c
  src/module.c
  src/server.h
  tests/unit/scan.tcl
Labels: release-notes

#12707 Handle all CLUSTER_REDIR_ error code when verifying Lua.
  src/script.c
Labels: release-notes

#12751 Add an explanation for URI with -u in redis-cli --help
  src/redis-benchmark.c
  src/redis-cli.c
Labels: state:to-be-merged, class:text

#12735 redis-cli --bigkeys ,--hotkeys and --memkeys to replica in cluster mode
  src/redis-cli.c
Labels: release-notes

#12811 clarify the comment of findSlotByKeyIndex function
  src/db.c
Labels: class:text
