Repository redis/redis, pull requests merged in 2023-06, with the labels that each got.

#12301 Fix XREADGROUP BLOCK stuck in endless loop
  src/blocked.c
  tests/unit/type/stream-cgroups.tcl
Labels: release-notes

#12269 Allow cluster slots/shards api to respond during loading
  src/commands.def
  src/commands/cluster-shards.json
  src/commands/cluster-slots.json
  tests/cluster/tests/28-cluster-shards.tcl
Labels: state:major-decision, release-notes, approval-needed

#12177 improve performance for keys with expiration time
  src/db.c
Labels: action:run-benchmark

#9564 Cluster human readable nodename feature
  redis.conf
  src/cluster.c
  src/cluster.h
  src/config.c
  src/server.h
  tests/support/cluster_util.tcl
  tests/test_helper.tcl
  tests/unit/cluster/hostnames.tcl
  tests/unit/cluster/human-announced-nodename.tcl
Labels: state:major-decision, release-notes

#12315 Set Jemalloc --disable-cache-oblivious to reduce memory overhead
  deps/Makefile
Labels: action:run-benchmark

#9052 zrangeGenericCommand add check for negative offset.
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: state:to-be-merged

#12250 use embedded string object and more efficient ll2string for long long value convert to string
  src/geo.c
  src/module.c
  src/object.c
  src/rdb.c
  src/sds.c
  src/server.h
Labels: action:run-benchmark

#12326 Fix broken protocol when PUBLISH emits local push inside MULTI
  src/networking.c
  src/server.c
  src/server.h
  tests/modules/publish.c
  tests/unit/moduleapi/misc.tcl
  tests/unit/moduleapi/publish.tcl
  tests/unit/pubsub.tcl
Labels: state:major-decision, breaking-change

#12321 Align RM_ReplyWithErrorFormat with RM_ReplyWithError
  src/module.c
  tests/unit/moduleapi/reply.tcl
Labels: state:major-decision, breaking-change

#12233 Support TLS service when "tls-cluster" is not enabled and persist both plain and TLS port in nodes.conf
  src/cluster.c
  src/cluster.h
  src/connection.h
  src/module.c
  tests/support/cluster_util.tcl
  tests/support/server.tcl
  tests/test_helper.tcl
  tests/unit/cluster/cluster-response-tls.tcl
  tests/unit/other.tcl
Labels: release-notes

#12339 Adding of O3 on linking stage for OPTIMIZATION=-O3 cases
  src/Makefile
Labels: action:run-benchmark

#12209 improve performance for scan command when matching pattern or data type
  src/db.c
  src/module.c
  src/server.h
  tests/unit/moduleapi/datatype.tcl
  tests/unit/scan.tcl
Labels: state:major-decision
