Repository redis/redis, pull requests merged in 2023-12, with the labels that each got.

#12754 Optimize KEYS when pattern includes hashtag and implies a single slot.
  src/db.c
  tests/unit/keyspace.tcl
Labels: release-notes, approval-needed

#12244 Fix outdated LFU comments to eliminate confusion
  src/evict.c
Labels: class:text

#12849 Add metric to INFO CLIENTS: pubsub_clients.
  src/networking.c
  src/pubsub.c
  src/server.c
  src/server.h
  tests/unit/info.tcl
Labels: release-notes

#12728 Support by/get options for sort(_ro) in cluster mode when pattern implies slot.
  src/sort.c
  tests/unit/sort.tcl
Labels: state:major-decision, release-notes, approval-needed

#11315 redis-cli adds -4 / -6 options to determine IPV4 / IPV6 priority in DNS lookup
  src/anet.c
  src/anet.h
  src/redis-cli.c
  tests/unit/cluster/cli.tcl
Labels: release-notes

#12171 Don't disconnect all clients in ACL LOAD
  src/acl.c
  src/adlist.c
  tests/assets/user.acl
  tests/unit/acl.tcl
Labels: release-notes
