Repository redis/redis, pull requests merged in 2023-01, with the labels that each got.

#11012 reprocess command when client is unblocked on keys
  src/blocked.c
  src/cluster.c
  src/db.c
  src/dict.h
  src/module.c
  src/networking.c
  src/replication.c
  src/script.c
  src/script_lua.c
  src/server.c
  src/server.h
  src/t_list.c
  src/t_stream.c
  src/t_zset.c
  src/timeout.c
  tests/integration/replication.tcl
  tests/modules/misc.c
  tests/unit/introspection.tcl
  tests/unit/moduleapi/propagate.tcl
  tests/unit/slowlog.tcl
  tests/unit/type/list.tcl
  tests/unit/type/stream-cgroups.tcl
Labels: state:major-decision, release-notes, approval-needed

#11594 Optimize the performance of msetnx command by call lookupkey only once
  src/t_string.c
Labels: action:run-benchmark

#11688 Blocking command with a 0.001 seconds timeout blocks indefinitely
  src/timeout.c
  tests/unit/type/list.tcl
Labels: release-notes

#11675 Fixes typo (double word) in memory overcommit message
  src/syscheck.c
Labels: class:text

#11465 Make dictEntry opaque
  src/cluster.c
  src/cluster.h
  src/config.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/eval.c
  src/expire.c
  src/functions.c
  src/module.c
  src/object.c
  src/pubsub.c
  src/redis-cli.c
  src/server.c
  src/server.h
  src/t_zset.c
Labels: action:run-benchmark

#11595 Key as dict entry - memory optimization for sets
  src/defrag.c
  src/dict.c
  src/dict.h
  src/server.c
  src/t_set.c
  src/zmalloc.c
Labels: release-notes, action:run-benchmark

#11725 Optimize the performance of sdscatrepr in printable characters
  src/sds.c
Labels: action:run-benchmark
