Repository redis/redis, pull requests merged in 2023-02, with the labels that each got.

#11752 Propagate message to a node only if the cluster link is healthy.
  src/cluster.c
  src/cluster.h
  src/debug.c
  tests/unit/cluster/links.tcl
Labels: release-notes

#11477 Added fields to ACL LOG error entries for precise time logging
  src/acl.c
  src/commands.c
  src/commands/acl-log.json
  tests/unit/acl.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#11779 Optimize ZRANGE replies WITHSCORES in case of integer scores
  src/networking.c
  src/util.c
  tests/integration/rdb.tcl
Labels: release-notes, action:run-benchmark

#11788 SCAN/RANDOMKEY and lazy-expire
  src/commands.c
  src/commands/randomkey.json
  src/commands/scan.json
  src/db.c
  src/server.c
  src/server.h
  tests/unit/expire.tcl
Labels: release-notes, approval-needed

#11770 Cleanup around script_caller, fix tracking of scripts and ACL logging for RM_Call
  src/acl.c
  src/aof.c
  src/debug.c
  src/eval.c
  src/module.c
  src/networking.c
  src/script.c
  src/script.h
  src/server.c
  src/server.h
  src/tracking.c
  tests/integration/replication.tcl
  tests/modules/usercall.c
  tests/unit/acl.tcl
  tests/unit/moduleapi/misc.tcl
  tests/unit/moduleapi/usercall.tcl
  tests/unit/tracking.tcl
Labels: state:major-decision, release-notes, breaking-change

#11814 Prevent Redis from crashing from key tracking invalidations
  src/tracking.c
  tests/unit/tracking.tcl
Labels: release-notes

#11483 Add CLIENT NO-TOUCH for clients to run commands without affecting LRU/LFU of keys
  src/commands.c
  src/commands/client-no-touch.json
  src/db.c
  src/networking.c
  src/server.h
  tests/unit/introspection-2.tcl
Labels: state:needs-doc-pr, release-notes
