Repository redis/redis, pull requests merged in 2023-03, with the labels that each got.

#11885 Compact Redis nodes in stream listpacks
  src/object.c
  src/t_stream.c
Labels: release-notes

#11799 Fix misleading error message in XREADGROUP
  src/t_stream.c
Labels: state:to-be-merged

#11713 Implementing the WAITAOF command (issue #10505)
  src/aof.c
  src/bio.c
  src/bio.h
  src/blocked.c
  src/commands.c
  src/commands/waitaof.json
  src/config.c
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  tests/support/util.tcl
  tests/unit/wait.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes

#10555 cleanup NBSP characters in comments
  src/module.c
  src/networking.c
  src/replication.c
  src/resp_parser.c
  src/script_lua.c
Labels: class:text

#11659 Custom authentication for Modules
  runtest-moduleapi
  src/acl.c
  src/module.c
  src/networking.c
  src/redismodule.h
  src/server.h
  tests/modules/Makefile
  tests/modules/auth.c
  tests/modules/moduleauthtwo.c
  tests/unit/acl.tcl
  tests/unit/moduleapi/moduleauth.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change

#11911 Bump codespell to 2.2.4, fix typos and outupdated comments
  .codespell/requirements.txt
  redis.conf
  src/blocked.c
  src/hyperloglog.c
  src/listpack.c
  src/networking.c
  src/script.c
  src/server.c
  src/server.h
  src/t_list.c
  tests/unit/pause.tcl
  tests/unit/type/list.tcl
Labels: class:text

#11873 redis-cli: Accept commands in subscribed mode
  deps/linenoise/linenoise.c
  src/redis-cli.c
  tests/integration/redis-cli.tcl
Labels: release-notes

#11708 Module commands to have ACL categories.
  src/acl.c
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/aclcheck.c
  tests/modules/datatype.c
  tests/modules/moduleconfigs.c
  tests/unit/moduleapi/aclcheck.tcl
  tests/unit/moduleapi/datatype.tcl
  tests/unit/moduleapi/moduleconfigs.tcl
Labels: state:major-decision, release-notes, approval-needed, breaking-change

#11758 Allow clients to report name and version
  src/commands.c
  src/commands/client-setinfo.json
  src/networking.c
  src/server.h
  tests/unit/introspection.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes

#11970 Fixed tracking of command duration for multi/eval/module/wait
  src/blocked.c
  src/module.c
  src/networking.c
  src/replication.c
  src/server.c
Labels: release-notes
