Repository redis/redis, pull requests merged in 2023-10, with the labels that each got.

#12604 Fix crash when running rebalance command in a mixed cluster of 7.0 and 7.2
  src/cluster.c
Labels: release-notes

#12596 support XREAD[GROUP] with BLOCK option in scripts
  src/commands.def
  src/commands/xread.json
  src/t_stream.c
  tests/unit/scripting.tcl
Labels: release-notes

#12577 Unsubscribe all clients from replica for shard channel if the master ownership changes
  src/cluster.c
  tests/cluster/tests/25-pubsubshard-slot-migration.tcl
Labels: release-notes

#11695 Replace cluster metadata with slot specific dictionaries
  src/aof.c
  src/cluster.c
  src/cluster.h
  src/db.c
  src/debug.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/evict.c
  src/expire.c
  src/lazyfree.c
  src/module.c
  src/multi.c
  src/object.c
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_set.c
  src/t_zset.c
  tests/support/util.tcl
  tests/unit/cluster/scripting.tcl
  tests/unit/expire.tcl
  tests/unit/memefficiency.tcl
  tests/unit/scan.tcl
Labels: state:major-decision, release-notes, action:run-benchmark

#12687 Update comment around propagateDeletion
  src/cluster.c
  src/db.c
Labels: class:text

#12693 Fix fd leak causing deleted files to remain open and eat disk space
  src/replication.c
Labels: release-notes
