Repository redis/redis, pull requests merged in 2023-05, with the labels that each got.

#11945 [redis-benchmark] Adding --seed option to seed the RNG
  src/redis-benchmark.c
Labels: approval-needed

#12088 Free backlog only if rsi is invalid when master reboot
  src/server.c
  tests/integration/psync2-master-restart.tcl
Labels: release-notes

#12019 Minor performance improvement to SADD and HSET
  src/server.h
  src/t_hash.c
  src/t_set.c
Labels: release-notes, action:run-benchmark

#12144 Remove repetitive the
  src/blocked.c
  src/commands/append.json
  tests/unit/cluster/cli.tcl
Labels: class:text

#12136 Correct zrangeGenericCommand comment
  src/t_zset.c
Labels: class:text

#12042 redis-cli - add option --count for scan
  src/redis-cli.c
Labels: release-notes, approval-needed

#11963 Add basic eventloop latency measurement.
  src/latency.c
  src/latency.h
  src/server.c
  src/server.h
  tests/unit/info.tcl
Labels: action:run-benchmark

#12185 Performance improvement to ZADD and ZRANGESTORE, convert to skiplist and expand dict in advance
  src/t_zset.c
  tests/unit/type/zset.tcl
Labels: action:run-benchmark

#12166 Exclude aux fields from "cluster nodes" and "cluster replicas" output
  src/cluster.c
  src/cluster.h
  src/debug.c
  tests/cluster/cluster.tcl
  tests/cluster/tests/28-cluster-shards.tcl
  tests/unit/cluster/misc.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#11626 postpone the initialization of oject's lru&lfu until it is added to the db as a value object
  src/db.c
  src/evict.c
  src/object.c
  src/server.c
  src/server.h
  tests/unit/maxmemory.tcl
Labels: action:run-benchmark

#12220 Fix WAIT for clients being blocked in a module command
  src/module.c
  tests/modules/blockonkeys.c
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/moduleapi/blockonkeys.tcl
Labels: release-notes
