Repository redis/redis, pull requests merged in 2023-04, with the labels that each got.

#11992 Disconnect pub-sub subscribers when revoking `allchannels` permission
  src/acl.c
  tests/unit/acl.tcl
Labels: release-notes

#11852 Add RM_RdbLoad and RM_RdbSave module API functions
  runtest-moduleapi
  src/module.c
  src/rdb.c
  src/rdb.h
  src/redismodule.h
  tests/modules/Makefile
  tests/modules/rdbloadsave.c
  tests/unit/moduleapi/rdbloadsave.tcl
Labels: state:major-decision, release-notes, approval-needed

#11982 Use dummy allocator to make accesses defined as per standard
  src/debug.c
  src/listpack_malloc.h
  src/module.c
  src/networking.c
  src/zmalloc.c
  src/zmalloc.h
Labels: action:run-benchmark

#12022 Fix redis_check_rdb() hang when rdb is FIFO
  src/redis-check-rdb.c
Labels: release-notes

#12036 improve performance of keys command by using static objects
  src/db.c
Labels: action:run-benchmark

#12025 iterate clients fairly in clientsCron()
  src/server.c
Labels: release-notes
