Repository redis/redis, pull requests merged in 2023-07, with the labels that each got.

#12372 redis-benchmark: add documentation for the amount of clients needed
  src/redis-benchmark.c
Labels: state:to-be-merged, class:text

#12344 Process loss of slot ownership in cluster bus
  src/cluster.c
  src/cluster.h
  tests/cluster/tests/15-cluster-slots.tcl
Labels: release-notes

#12411 Hide unnecessary comma in front of empty hostname in the return of CLUSTER NODES.
  src/cluster.c
Labels: release-notes

#12273 redis-cli: use previous hostip when not provided by redis cluster server
  src/redis-cli.c
  tests/unit/cluster/cli.tcl
Labels: state:to-be-merged, release-notes
