Repository redis/redis, pull requests merged in 2024-09, with the labels that each got.

#13495 Reply LOADING on replica while flushing the db
  src/aof.c
  src/config.c
  src/db.c
  src/debug.c
  src/module.c
  src/rdb.c
  src/rdb.h
  src/replication.c
  src/server.c
  src/server.h
  tests/cluster/tests/14-consistency-check.tcl
  tests/cluster/tests/28-cluster-shards.tcl
  tests/cluster/tests/includes/init-tests.tcl
  tests/integration/aof.tcl
  tests/integration/replication.tcl
Labels: release-notes

#13490 Optimize the HELLO command reply
  src/module.c
  src/networking.c
  src/server.h
Labels: action:run-benchmark

#13499 Created specific SMEMBERS command logic which avoids sinterGenericCommand, and minimizes processing and memory overhead
  src/commands.def
  src/commands/smembers.json
  src/server.h
  src/t_set.c
Labels: action:run-benchmark

#13509 Added new defrag API to allocate and free raw memory.
  src/defrag.c
  src/dict.h
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/defragtest.c
  tests/unit/moduleapi/defrag.tcl
Labels: release-notes

#13494 changed addReplyHumanLongDouble to addReplyDouble in georadiusGeneric and geoposCommand
  src/geo.c
Labels: release-notes, action:run-benchmark

#13503 Avoid overhead of comparision function pointer calls in lpFind()
  src/listpack.c
Labels: action:run-benchmark

#13488 Introduce reusable query buffer for client reads
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  tests/unit/querybuf.tcl
Labels: release-notes, action:run-benchmark

#13425 HFE - Simplify logic of HGETALL
  src/t_hash.c
  tests/unit/type/hash-field-expire.tcl
Labels: action:run-benchmark

#13520 Replace usage of _addReplyLongLongWithPrefix with specific bulk/mbulk functions to reduce condition checks in hotpath.
  src/networking.c
Labels: action:run-benchmark

#13566 Optimize ZUNION[STORE] by avoiding redundant temporary dict usage
  src/t_zset.c
Labels: action:run-benchmark

#13567 Use hashtable as the default type of temp set object during sunion/sdiff
  src/t_set.c
Labels: action:run-benchmark
