Repository redis/redis, pull requests merged in 2024-03, with the labels that each got.

#12913 Add overhead of all DBs and rehashing dict count to info.
  src/commands/memory-stats.json
  src/kvstore.c
  src/kvstore.h
  src/object.c
  src/server.c
  src/server.h
  tests/unit/info.tcl
  tests/unit/other.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#12986 Pick random slot for a node to distribute operation across slots in redis-benchmark
  src/redis-benchmark.c
Labels: release-notes

#13069 Add API RedisModule_ClusterKeySlot and RedisModule_ClusterCanonicalKeyNameInSlot
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: state:major-decision, release-notes

#13117 Xread last entry in stream (#7388)
  src/t_stream.c
  tests/unit/type/stream.tcl
Labels: state:major-decision, approval-needed

#13108 Lua eval scripts first in first out LRU eviction
  src/eval.c
  src/lazyfree.c
  src/server.c
  src/server.h
  tests/unit/scripting.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed
