Repository redis/redis, pull requests merged in 2024-01, with the labels that each got.

#12838 Optimize performance when many clients [p|s]unsubscribe simultaneously
  src/pubsub.c
  src/server.c
  src/server.h
Labels: release-notes

#12897 Correct bytes_per_key computing.
  src/object.c
Labels: approval-needed

#12961 Revert multi OOM limit and add multi buffer limit
  redis.conf
  src/networking.c
  src/server.c
Labels: release-notes

#12985 Add RM_TryCalloc() and RM_TryRealloc()
  src/module.c
  src/redismodule.h
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
Labels: release-notes, approval-needed

#10609 Adds connection timeout option to redis-cli
  src/cli_common.c
  src/cli_common.h
  src/redis-cli.c
Labels: state:major-decision, release-notes, approval-needed

#12299 Implement `CLIENT KILL MAXAGE <maxage>`
  src/commands.def
  src/commands/client-kill.json
  src/networking.c
  tests/unit/introspection.tcl
Labels: state:needs-doc-pr, release-notes, approval-needed

#12765 Add novalues option to command HSCAN.
  src/commands.def
  src/commands/hscan.json
  src/db.c
  tests/unit/scan.tcl
Labels: release-notes
