Repository redis/redis, pull requests merged in 2024-08, with the labels that each got.

#13411 Fix wrong dbnum showed in redis-cli after client reconnected
  src/redis-cli.c
  tests/integration/redis-cli.tcl
Labels: state:to-be-merged, release-notes

#13218 Replace bit shift with __builtin_ctzll in HyperLogLog
  src/hyperloglog.c
Labels: state:to-be-merged

#13443 Ensure validity of myself as master or replica when loading cluster config
  src/cluster_legacy.c
Labels: release-notes

#13465 Pass extensions to node if extension processing is handled by it
  src/cluster_legacy.c
  src/cluster_legacy.h
  tests/unit/cluster/hostnames.tcl
Labels: release-notes

#13473 Fix incorrect lag due to trimming stream via XTRIM command
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: release-notes

#13431 Avoid used_memory contention when update from multiple threads.
  src/config.h
  src/networking.c
  src/zmalloc.c
Labels: release-notes, action:run-benchmark

#12395 improve performance for scan command when matching data type
  src/db.c
  tests/unit/scan.tcl
Labels: breaking-change

#12272 Improve GETRANGE command behavior
  src/t_string.c
  tests/unit/type/string.tcl
Labels: release-notes, breaking-change

#13489 MOD-7645: Return module commands in ACL CAT
  src/acl.c
Labels: release-notes

#13299 Remove variable expired in expireSlaveKeys() to prevent confusing the compiler
  src/expire.c
Labels: class:cleanup
