Repository redis/redis, pull requests merged in 2024-02, with the labels that each got.

#12925 Refine the purpose of rdb saving with accurate flags
  src/rdb.c
  src/rdb.h
  src/replication.c
Labels: release-notes

#13008 Improve error handling in connSocketBlockingConnect for various connction failures
  src/socket.c
Labels: state:to-be-merged

#12966 Add metrics for WATCH
  src/blocked.c
  src/multi.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/info.tcl
  tests/unit/introspection.tcl
Labels: state:needs-doc-pr, state:major-decision, release-notes, approval-needed

#12973 add -fno-omit-frame-pointer to default complication flags
  src/Makefile
Labels: action:run-benchmark

#12996 Defragger improvements around large bins
  src/defrag.c
  src/object.c
  src/server.c
  src/server.h
  src/zmalloc.c
  src/zmalloc.h
Labels: state:needs-doc-pr, release-notes, approval-needed

#12971 Expose lua os.clock() api
  deps/lua/src/loslib.c
  src/script_lua.c
  tests/unit/scripting.tcl
Labels: state:needs-doc-pr, state:major-decision, approval-needed
