Repository redis/redis, pull requests merged in 2024-05, with the labels that each got.

#13276 Have consistent behavior of SPUBLISH within multi/exec like regular command
  src/cluster.c
  tests/test_helper.tcl
  tests/unit/cluster/sharded-pubsub.tcl
Labels: release-notes

#13246 Log the real reason for why posix_fadvise failed
  src/util.c
Labels: state:to-be-merged

#12826 redis-cli --keystats and --keystats-samples with --top and --cursor
  src/Makefile
  src/redis-cli.c
Labels: state:to-be-merged

#13303 Hash Field Expiration
  src/Makefile
  src/aof.c
  src/cluster.c
  src/commands.def
  src/commands/hexpire.json
  src/commands/hexpireat.json
  src/commands/hexpiretime.json
  src/commands/hpersist.json
  src/commands/hpexpire.json
  src/commands/hpexpireat.json
  src/commands/hpexpiretime.json
  src/commands/hpttl.json
  src/commands/httl.json
  src/db.c
  src/debug.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/ebuckets.c
  src/ebuckets.h
  src/expire.c
  src/lazyfree.c
  src/listpack.c
  src/listpack.h
  src/module.c
  src/mstr.c
  src/mstr.h
  src/networking.c
  src/notify.c
  src/object.c
  src/rax.c
  src/rax.h
  src/rdb.c
  src/rdb.h
  src/redis-check-rdb.c
  src/server.c
  src/server.h
  src/sort.c
  src/t_hash.c
  src/t_set.c
  src/t_zset.c
  src/testhelp.h
  tests/integration/corrupt-dump-fuzzer.tcl
  tests/integration/corrupt-dump.tcl
  tests/integration/psync2-master-restart.tcl
  tests/integration/rdb.tcl
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/memefficiency.tcl
  tests/unit/other.tcl
  tests/unit/pubsub.tcl
  tests/unit/scan.tcl
  tests/unit/type/hash-field-expire.tcl
Labels: state:needs-doc-pr, release-notes

#13220 dynamically list test files
  tests/support/util.tcl
  tests/test_helper.tcl
  tests/unit/keyspace.tcl
  tests/unit/type/hash.tcl
  tests/unit/type/list-2.tcl
  tests/unit/type/list-common.tcl
  tests/unit/type/list.tcl
Labels: state:to-be-merged

#13274 Free current client asynchronously after user permissions changes
  src/acl.c
  src/module.c
  src/networking.c
  src/server.h
  tests/unit/acl.tcl
Labels: release-notes
