Repository redis/redis, pull requests merged in 2024-12, with the labels that each got.

#13646 Optimize dictFind with prefetching and branch prediction hints.
  src/config.h
  src/dict.c
Labels: action:run-benchmark

#13652 Improve listpack Handling and Decoding Efficiency: 16.3% improvement on LRANGE command
  src/listpack.c
  src/listpack.h
  src/networking.c
  src/t_list.c
Labels: action:run-benchmark

#13676 Modules API: new HashFieldMinExpire(). Add flag REDISMODULE_HASH_EXPIRE_TIME to HashGet().
  src/module.c
  src/redismodule.h
  src/server.h
  src/sort.c
  src/t_hash.c
  tests/modules/hash.c
  tests/unit/moduleapi/hash.tcl
Labels: release-notes

#13655 Avoid unnecessary hfield Creation/Deletion on updates in hashTypeSet. HSET updates improvement of ~10%
  src/defrag.c
  src/dict.c
  src/dict.h
  src/kvstore.c
  src/kvstore.h
  src/t_hash.c
Labels: action:run-benchmark

#13672 Fix bug in PFMERGE command
  src/hyperloglog.c
  tests/unit/hyperloglog.tcl
Labels: release-notes

#13665 Async IO threads
  redis.conf
  src/Makefile
  src/ae.c
  src/ae.h
  src/commands.def
  src/commands/client-list.json
  src/config.c
  src/config.h
  src/connection.c
  src/connection.h
  src/debug.c
  src/eventnotifier.c
  src/eventnotifier.h
  src/iothread.c
  src/multi.c
  src/networking.c
  src/server.c
  src/server.h
  src/socket.c
  src/tls.c
  src/tracking.c
  src/unix.c
  tests/integration/shutdown.tcl
  tests/support/util.tcl
  tests/unit/client-eviction.tcl
  tests/unit/info.tcl
  tests/unit/introspection.tcl
  tests/unit/maxmemory.tcl
  tests/unit/memefficiency.tcl
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/pubsub.tcl
  tests/unit/pubsubshard.tcl
  tests/unit/querybuf.tcl
  tests/unit/type/list.tcl
Labels: state:needs-doc-pr, release-notes

#13695 Async IO Threads
  redis.conf
  src/Makefile
  src/ae.c
  src/ae.h
  src/cluster.c
  src/cluster_legacy.c
  src/commands.def
  src/commands/client-list.json
  src/config.c
  src/config.h
  src/connection.c
  src/connection.h
  src/debug.c
  src/eventnotifier.c
  src/eventnotifier.h
  src/iothread.c
  src/multi.c
  src/networking.c
  src/replication.c
  src/server.c
  src/server.h
  src/socket.c
  src/tls.c
  src/tracking.c
  src/unix.c
  tests/integration/shutdown.tcl
  tests/support/util.tcl
  tests/unit/client-eviction.tcl
  tests/unit/info.tcl
  tests/unit/introspection.tcl
  tests/unit/lazyfree.tcl
  tests/unit/maxmemory.tcl
  tests/unit/memefficiency.tcl
  tests/unit/moduleapi/blockedclient.tcl
  tests/unit/pubsub.tcl
  tests/unit/pubsubshard.tcl
  tests/unit/querybuf.tcl
  tests/unit/type/list.tcl
Labels: release-notes
