Repository redis/redis, pull requests merged in 2025-07, with the labels that each got.

#14039 Add CLUSTER SLOT-STATS command
  redis.conf
  src/Makefile
  src/blocked.c
  src/cluster.c
  src/cluster.h
  src/cluster_legacy.c
  src/cluster_legacy.h
  src/cluster_slot_stats.c
  src/cluster_slot_stats.h
  src/commands.def
  src/commands/cluster-slot-stats.json
  src/config.c
  src/db.c
  src/networking.c
  src/pubsub.c
  src/replication.c
  src/script.c
  src/server.c
  src/server.h
  tests/support/cluster_util.tcl
  tests/unit/cluster/slot-stats.tcl
Labels: state:needs-doc-pr, release-notes, action:run-benchmark

#14162 Fix crash due to incorrect event deletion of evport
  src/ae_evport.c
Labels: release-notes

#14051 Module set/get config API
  runtest-moduleapi
  src/config.c
  src/module.c
  src/redismodule.h
  src/server.h
  tests/modules/Makefile
  tests/modules/configaccess.c
  tests/unit/moduleapi/configaccess.tcl
Labels: state:needs-doc-pr, release-notes

#14163 Ensure empty error tables in scripts don't crash
  src/script_lua.c
  tests/unit/scripting.tcl
Labels: release-notes

#14141 Add new KSN types - overwritten and type_changed
  redis.conf
  src/cluster.c
  src/db.c
  src/module.c
  src/notify.c
  src/redismodule.h
  src/server.h
  tests/unit/pubsub.tcl
Labels: state:needs-doc-pr, release-notes

#14165 Only mark the client reprocessing flag when unblocked on keys
  src/blocked.c
  src/server.c
  src/server.h
  tests/unit/type/list.tcl
Labels: release-notes

#14164 CLIENT UNBLOCK should't be able to unpause paused clients
  src/blocked.c
  src/networking.c
  src/server.h
  tests/unit/pause.tcl
  tests/unit/wait.tcl
Labels: release-notes
