Repository redis/redis, pull requests merged in 2025-09, with the labels that each got.

#14259 Fix: Validate ENTRIESREAD in XGROUP command
  src/t_stream.c
  tests/unit/type/stream-cgroups.tcl
Labels: state:to-be-merged, release-notes

#14319 Fix crash during lua script defrag
  src/defrag.c
  src/replication.c
  src/server.c
Labels: release-notes

#14330 Fix defrag issues for pubsub and lua
  src/defrag.c
  src/dict.c
  src/dict.h
  src/eval.c
Labels: release-notes

#14323 Fix defrag issues for stream defrag and HFE
  src/defrag.c
  src/ebuckets.c
Labels: release-notes

#14317 [vector sets] Add --ollama-url option to configure embedding server
  modules/vector-sets/examples/cli-tool/cli.py
Labels: state:to-be-merged
