Repository redis/redis, pull requests merged in 2025-05, with the labels that each got.

#13903 Reduce the call of ERR_clear_error
  src/tls.c
Labels: state:to-be-merged

#13805 Fix typo in replication state log message
  src/replication.c
Labels: state:to-be-merged

#13809 Redis-cli gets RDB by RDB channel
  src/rdb.c
  src/replication.c
  src/server.h
  tests/integration/redis-cli.tcl
  tmp
Labels: state:to-be-merged

#13923 Fix various KEYSIZES enumeration issues
  src/db.c
  src/hyperloglog.c
  src/kvstore.h
  src/module.c
  src/server.c
  src/server.h
  src/t_hash.c
  src/t_list.c
  src/t_set.c
  src/t_string.c
  src/t_zset.c
  tests/unit/info-keysizes.tcl
  tests/unit/moduleapi/hash.tcl
  tests/unit/moduleapi/list.tcl
  tests/unit/moduleapi/zset.tcl
Labels: action:run-benchmark

#13944 Input output traffic stats and command process count for each client.
  src/blocked.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/introspection.tcl
Labels: state:needs-doc-pr, release-notes

#13806 keyspace - Unify key and value & use dict no_value=1
  src/aof.c
  src/bitops.c
  src/blocked.c
  src/cluster.c
  src/cluster_legacy.c
  src/db.c
  src/debug.c
  src/defrag.c
  src/dict.c
  src/dict.h
  src/evict.c
  src/expire.c
  src/geo.c
  src/hyperloglog.c
  src/kvstore.c
  src/kvstore.h
  src/latency.c
  src/module.c
  src/multi.c
  src/object.c
  src/pubsub.c
  src/rdb.c
  src/redis-benchmark.c
  src/redis-cli.c
  src/redisassert.h
  src/sds.c
  src/sds.h
  src/sentinel.c
  src/server.c
  src/server.h
  src/sort.c
  src/t_hash.c
  src/t_list.c
  src/t_set.c
  src/t_stream.c
  src/t_string.c
  src/t_zset.c
  tests/integration/replication-rdbchannel.tcl
  tests/unit/info.tcl
  tests/unit/maxmemory.tcl
  tests/unit/memefficiency.tcl
  tests/unit/type/hash-field-expire.tcl
  tests/unit/type/incr.tcl
  tests/unit/type/string.tcl
Labels: action:run-benchmark

#13969 Make IO thread and main thread process in parallel and reduce notifications
  src/iothread.c
  src/server.c
  src/server.h
Labels: action:run-benchmark

#13842 Add support to defrag ebuckets incrementally
  src/defrag.c
  src/ebuckets.c
  src/ebuckets.h
  src/module.c
  src/rax.c
  src/rax.h
  tests/unit/memefficiency.tcl
Labels: state:to-be-merged

#13981 Optimize hash and zset with lpBatchAppend
  src/t_hash.c
  src/t_zset.c
Labels: state:to-be-merged

#13898 Implement DIFF, DIFF1, ANDOR and ONE for BITOP
  src/bitops.c
  src/commands.def
  src/commands/bitop.json
  tests/unit/bitops.tcl
Labels: state:needs-doc-pr, release-notes

#14040 Refine and optimize dbSetValue()
  src/crc64.c
  src/db.c
Labels: action:run-benchmark

#13968 Let IO threads free argv and rewrite objects
  src/db.c
  src/iothread.c
  src/networking.c
  src/server.h
Labels: action:run-benchmark

#14061 Add size_t cast for RM_call() in module tests
  tests/modules/aclcheck.c
  tests/modules/blockedclient.c
  tests/modules/commandfilter.c
  tests/modules/internalsecret.c
  tests/modules/misc.c
  tests/modules/usercall.c
Labels: state:to-be-merged

#14062 Add length check before content comparison in equalStringObjects
  src/object.c
Labels: state:to-be-merged

#13950 Add GETRANGE tests with negative indices
  tests/unit/type/string.tcl
Labels: state:to-be-merged

#14072 Avoid performing IO on coverage when child exits due to signal handler
  src/aof.c
  src/childinfo.c
  src/eval.c
  src/module.c
  src/rdb.c
  src/server.c
  src/server.h
Labels: state:to-be-merged
