Repository redis/redis, pull requests merged in 2025-08, with the labels that each got.

#14058 Add auto-repair options for broken AOF tail on startup
  redis.conf
  src/aof.c
  src/config.c
  src/server.h
  tests/integration/aof.tcl
Labels: state:needs-doc-pr, release-notes

#14299 Reduce the overhead for calculating jemalloc small bins frag
  src/zmalloc.c
Labels: action:run-benchmark

#14296 Add support to decode json empty array as lua array
  deps/lua/src/lua_cjson.c
  tests/unit/scripting.tcl
Labels: release-notes
