Repository redis/redis, pull requests merged in 2025-02, with the labels that each got.

#13774 Add flag for ability of a module context to execute debug commands
  src/module.c
  src/redismodule.h
  tests/modules/basics.c
  tests/unit/moduleapi/basics.tcl
Labels: release-notes

#13758 Start AOFRW before streaming repl buffer during fullsync
  src/commands/memory-stats.json
  src/object.c
  src/replication.c
  src/server.c
  src/server.h
  tests/integration/replication-rdbchannel.tcl
Labels: state:needs-doc-pr, release-notes

#13740 Add internal connection and command mechanism
  runtest-moduleapi
  src/acl.c
  src/debug.c
  src/module.c
  src/networking.c
  src/redismodule.h
  src/replication.c
  src/server.c
  src/server.h
  tests/modules/Makefile
  tests/modules/internalsecret.c
  tests/unit/moduleapi/internalsecret.tcl
Labels: release-notes

#13794 Missing --memkeys and --keystats for some options in redis-cli help text
  src/redis-cli.c
Labels: state:to-be-merged

#13793 Fix wrongly updating fsynced_reploff_pending when appendfsync=everysecond
  src/aof.c
Labels: release-notes

#13783 Memory Usage command LIST accuracy fix
  src/object.c
Labels: state:to-be-merged

#13798 Add HGETDEL, HGETEX and HSETEX hash commands
  src/commands.def
  src/commands/hgetdel.json
  src/commands/hgetex.json
  src/commands/hsetex.json
  src/server.c
  src/server.h
  src/t_hash.c
  tests/unit/info-keysizes.tcl
  tests/unit/pubsub.tcl
  tests/unit/type/hash-field-expire.tcl
  tests/unit/type/hash.tcl
Labels: state:needs-doc-pr, release-notes

#13800 Remove DENYOOM flag from hexpire command
  src/commands.def
  src/commands/hexpire.json
  src/commands/hexpireat.json
  src/commands/hpexpire.json
  src/commands/hpexpireat.json
Labels: release-notes

#13816 Add RM_DefragRedisModuleDict module API
  src/module.c
  src/redismodule.h
  tests/modules/defragtest.c
  tests/unit/moduleapi/defrag.tcl
Labels: state:needs-doc-pr, release-notes

#13764 Reuse lookupCommand data on consecutive same command calls on main thread
  src/server.c
Labels: action:run-benchmark

#13787 Avoid redundant calls to sdslen(c->querybuf) in processMultibulkBuffer
  src/networking.c
Labels: action:run-benchmark

#13792 Optimize dictFind by leveraging key length functions to avoid redundant computations.
  src/dict.c
  src/dict.h
  src/server.c
  src/server.h
Labels: action:run-benchmark

#13796 Reduce redundant key slot calculations on expiration checks
  src/db.c
Labels: action:run-benchmark
