Repository redis/redis, pull requests merged in 2025-06, with the labels that each got.

#13907 [sentinel] add tilt total count in sentinel info
  src/sentinel.c
Labels: state:to-be-merged, release-notes

#14092 Fix db->expires can't be defragged due to incorrect comparison in the expires stage
  src/defrag.c
  tests/unit/memefficiency.tcl
Labels: release-notes

#14088 Optimize COPY, RENAME and RESTORE commands with TTL
  src/cluster.c
  src/db.c
  src/object.c
  src/server.h
Labels: action:run-benchmark

#14089 Vset tests improvements
  modules/vector-sets/test.py
  modules/vector-sets/tests/persistence.py
Labels: state:to-be-merged

#14121 Improve SCAN performance by only performing expiration checks on DBs with volatile keys
  src/db.c
Labels: action:run-benchmark

#14131 Optimize quicklistCompare with optional string2ll caching.
  src/listpack.c
  src/listpack.h
  src/quicklist.c
  src/quicklist.h
  src/server.h
  src/t_list.c
  src/t_zset.c
Labels: state:to-be-merged

#13990 Record the time a replica attempts to connect with master
  src/replication.c
  src/server.c
  src/server.h
  tests/integration/replication.tcl
Labels: state:needs-doc-pr, release-notes

#14111 Fix generate-commands-json.py script (#14098)
  utils/generate-commands-json.py
Labels: state:to-be-merged

#13900 Reduce the main thread blocking in clients cron
  src/iothread.c
  src/networking.c
  src/server.c
  src/server.h
  tests/unit/info.tcl
  tests/unit/networking.tcl
  tests/unit/obuf-limits.tcl
Labels: action:run-benchmark
