Repository redis/redis, pull requests merged in 2025-03, with the labels that each got.

#13846 Cluster compatibility check
  redis.conf
  src/config.c
  src/db.c
  src/module.c
  src/networking.c
  src/script.c
  src/script.h
  src/server.c
  src/server.h
  src/sort.c
  tests/modules/misc.c
  tests/unit/moduleapi/misc.tcl
  tests/unit/other.tcl
Labels: state:needs-doc-pr, release-notes

#13883 Fix defrag when type/encoding changes during scan
  src/defrag.c
Labels: release-notes

#13896 Fix 'RESTORE can set LFU' test
  tests/unit/dump.tcl
Labels: state:to-be-merged

#13877 Ignore shardId updates from replica nodes
  src/cluster_legacy.c
Labels: release-notes

#13895 Put replica online when bgsave is done
  src/replication.c
  src/server.c
  tests/integration/replication-rdbchannel.tcl
Labels: release-notes
